### ISSUE TITLE
HU_SPCA_Identificar o adm do prestador de contas  - Sistema não permite incluir o mesmo presidente para período de gestão diferente.

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#1]
O sistema não permite cadastrar 2 presidentes com os mesmos dados (CPF, Título, Nome) para o mesmo prestador , porém com período de gestão diferente.
Ex.:
CPF: 00253052122
Título: 639870981287
Nome: PRESIDENTE 1
Período de Gestão: 01/06/2014 a 30/06/2014

CPF: 00253052122
Título: 639870981287
Nome: PRESIDENTE 1
Período de Gestão: 01/07/2014 a 31/07/2014

**Comment by flavioribeirom** [comment]
Liberado para teste

**Comment by marasb** [comment]
Corrigido.
