### ISSUE TITLE
HU_SPCA_Incluir Endereco do Prestador - Sistema nao retorna mensagem de obrigatoriedade

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#10]
Ao acessar pela primeira vez a tela Qualificação - Endereço para comunicação, clicou-se no botão Gravar.

O sistema não retornou mensagem informando quais eram os campos de preenchimento obrigatório.

Essa falha indica não observância ao CA4 da HU009

**Comment by AllanCruzRosa** [comment]
liberado para teste na versão 2.0.2

**Comment by marasb** [comment]
Defeito Corrigido.
