### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Ordem de apresentação da mensagem de alerta MSG084 está invertida.

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#100]
Na tela de registro de gasto, quando o usuário informa um CPF/CNPJ inválido o sistema está apresentando a mensagem MSG084 "O número do CPF/CNPJ é inválido. Verifique se o número informado confere com o existente no documento." antes da mensagem de confirmação MSG007 "Confirma operação?".
O caso de uso define que a mensagem de confirmação deve ser apresentada antes da mensagem de alerta MSG084.

**Comment by jadossantos** [comment]
Corrigido.

**Comment by marasb** [comment]
Defeito corrigido.
