### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Ocorreu um erro ao executar operação

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#101]
Na tela Pesquisa - Aplicação de Recursos quando o usuário informa os filtros 
"Número do documento de pagamento" e "Número de lançamento" com qualquer Operação e aciona o botão "Pesquisa" o sistema apresenta a mensagem: Ocorreu um erro ao executar operação.

![erro_ocorreu um erro ao executar operao](https://cloud.githubusercontent.com/assets/6304414/2731104/9d66aebc-c626-11e3-96ae-0fba2a236bb5.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.33

**Comment by marasb** [comment]
Defeito corrigido.
