### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Sistema não valida obrigatoriedade da natureza do gasto

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#102]
Na tela de cadastro de gasto (inclusão/alteração) quando o usuário seleciona um item na lista Natureza de Gasto para alteração, o usuário apaga os campos Código da Natureza do Gasto , Descrição da Natureza do Gasto e Valor e aciona o botão Atualizar Lista, o sistema não realiza a validação da obrigatoriedade dos campos.
Passos:
1) Acessar a tela de cadastro de gasto
2) Na lista natureza de gasto, selecionar um item para alteração.
3) Apagar os campos: Código da Natureza do Gasto , Descrição da Natureza do Gasto e Valor
4) Acionar o botão Atualizar Lista

**Comment by jadossantos** [comment]
Resolvido na versão 2.0.34.

**Comment by marasb** [comment]
Defeito corrigido.
