### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Mensagem MSG078 está divergente

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#103]
No cadastro de registro de gasto quando o sistema verifica que o valor do documento é diferente do somatório dos valores da natureza do gasto está sendo apresentada a mensagem "O Valor do Documento está diferente do Valor Total da Descrição do Gasto.", porém a mensagem correta é MSG078 "O valor do documento é diferente do somatório dos valores da natureza do gasto."

![erro _ mensagem 78 incorreta](https://cloud.githubusercontent.com/assets/6304414/2733845/ad0a801c-c64b-11e3-9336-26a14c165a3b.png)

**Comment by jadossantos** [comment]
Resolvido na versão 2.0.33.

**Comment by marasb** [comment]
RETORNO VERSÃO 2.0.34: O defeito persiste na versão 2.0.34.

![erro _ mensagem 78 incorreta - retorno](https://cloud.githubusercontent.com/assets/6304414/2734310/cf7f298e-c652-11e3-8325-d6b57417f300.png)

**Comment by jadossantos** [comment]
Erro de digitação da versão 2.0.35. E build não deve ter acontecido ainda.

**Comment by marasb** [comment]
Defeito corrigido.
