### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - A mensagem MSG078 está sendo apresentada indevidamente na tela de inclusão.

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#104]
O sistema está apresentando a mensagem MSG078 "O valor do documento é diferente do somatório dos valores da natureza do gasto", quando o sistema verifica que o valor do documento é diferente do somatório dos valores da natureza do gasto.
Porém esse fluxo (FA8) não está sendo chamado na inclusão, apenas na alteração.

![erro _ mensagem 78 incorreta](https://cloud.githubusercontent.com/assets/6304414/2733864/0bec5074-c64c-11e3-8a37-eb48feff3337.png)

**Comment by jadossantos** [comment]
O comportamento acontece. Correção apenas da mensagem que foi igual ao ticket issues/103.

**Comment by marasb** [comment]
RETORNO.
A mensagem não deve aparecer a inclusão apenas na alteração.

**Comment by jadossantos** [comment]
Corrigido na versão 2.0.36.

**Comment by marasb** [comment]
Defeito corrigido.
