### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Faltam títulos Registro de Gasto e Registro de pagamento na grid

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#107]
Na tela Pesquisa - Aplicação de Recurso não estão sendo apresentados os títulos "Registro do Gasto" e "Registro do Pagamento" na grid de registro de gastos.
No caso de uso esses títulos foram definidos.

![erro _ erro grid de aplicao](https://cloud.githubusercontent.com/assets/6304414/2769202/5b407ba4-ca4e-11e3-8b24-db4e98c8879d.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido.
