### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Erro na pesquisa de fornecedor pelo número do CPF/CNPJ

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#108]
O sistema não está retornando resultado quando o usuário realiza a pesquisa de fornecedor pelo número do CPF/CNPJ.

![erro _erro na pesquisa de fornecedor pelo cpf-cnpj](https://cloud.githubusercontent.com/assets/6304414/2776867/3bca8354-cadb-11e3-8482-b0dbd26ae288.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.39

**Comment by marasb** [comment]
Defeito Corrigido.
