### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Erro no tamanho do campo Nome/Razão Social na tela de pesquisa de fornecedor

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#109]
Na tela de Pesquisa de fornecedor o campo Nome/Razão Social está aceitando apenas 70 caracteres, sendo que o caso de uso define 252.

**Comment by rsantanam** [comment]
A documentação deve ser atualizada com os tamanhos correspondentes ao do Modelo de Dados.

**Comment by marasb** [comment]
Os casos de uso foram alterados para correção do tamanho dos campos Nome/Razão Social que estava especificado com tamanho 252 mas a base de dados está especificada com tamanho 70 para Nome e tamanho 300 para Razão Social.

Na tela de pesquisa de fornecedor vamos deixar o tamanho máximo de 300.

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.45

**Comment by marasb** [comment]
defeito corrigido.
