### ISSUE TITLE
HU_SPCA_Alterar Endereco do Prestador - Sistema permite ao usuário com perfil consulta alterar os endereço do prestador

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#11]
Ao acessar a funcionalidade Alterar Endereço do Prestador (Endereço do Prestador de Contas) com um usuário perfil Consulta, o sistema está permitindo alterar os dados do endereço do prestador.
Sendo que de acordo com a história: "..Esta opção poderá ser acessada pelos usuários com perfil “Administrador”, “Operador” e “Consulta”. O usuário com perfil “Consulta” poderá somente visualizar as informações."

**Comment by flavioribeirom** [comment]
Liberado para teste

**Comment by wesleyreis** [comment]
Para o administrador e operador o botão Gravar não está sendo apresentado, porém, para o usuário como perfil de Consulta o mesmo é apresentado.

**Comment by AllanCruzRosa** [comment]
Liberado para teste.

**Comment by wesleyreis** [comment]
Defeito corrigido.

Versão 2.0.2 do ambiente de integração (http://integracao.happs.tse.jus.br:9080/spca-ic/).
