### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Erro no tipo do campo Número do Documento

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#110]
Na tela de pesquisa de fornecedor o campo Número do Documento está aceitando apenas caracteres do tipo Numérico, porém o caso de uso define o tipo de caracteres Alfanumérico.

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.39

**Comment by marasb** [comment]
Defeito corrigido.
