### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Erro nos hints da pesquisa de fornecedor

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#111]
Na tela de pesquisa de fornecedor o sistema não esta apresentando os hints dos botões abaixo:
Pesquisar    - O sistema dever apresentar o Hint MH031.
Primeira Página - O sistema dever apresentar o Hint MH005.
Página Anterior - O sistema dever apresentar o Hint MH006.
Numeração de página - O sistema dever apresentar o Hint MH007.
Última Página - O sistema dever apresentar o Hint MH008.

![erro _ erro no hint da tela de pesquisa de fornecedor](https://cloud.githubusercontent.com/assets/6304414/2776993/872caab4-cadd-11e3-9d9d-0c2c07fe90f7.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido.
