### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - O sistema não apresenta a mensagem de confirmação na exclusão de fornecedor

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#112]
O sistema não está apresentando a mensagem MSG007 "Confirma operação?", quando o usuário solicita a exclusão dos dados do fornecedor/prestador de serviço.

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.40

**Comment by marasb** [comment]
Defeito corrigido.
