### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Erro na ordem de apresentação da mensagem MSG089.

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#114]
Quando o usuário informa data do pagamento maior que a data atual o sistema está apresentando primeiro a mensagem MSG089 "A data do pagamento é maior que a data atual." e depois a mensagem de confirmação, porém o caso de uso define a seguinte ordem.
FB.5.   O sistema apresenta a mensagem MSG007.
FB.6.   O ator confirma a mensagem.
FB.7.   O sistema valida os dados informados. [RN83][RN47][FE 1][FE 2]
FB.8.   O sistema verifica que a data do pagamento é menor ou igual a data atual. [FA 2

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.41

**Comment by marasb** [comment]
Defeito corrigido.
