### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Erro na ordem de apresentação da mensagem MSG090.

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#115]
Quando o usuário informa data do pagamento menor que a data da emissão/contratação do fornecedor/prestador de serviço sistema está apresentando primeiro a mensagem MSG090"A data do pagamento é menor que a data da emissão/contratação do fornecedor/prestador de serviço." e depois a mensagem de confirmação, porém o caso de uso define a seguinte ordem.
FB.5. O sistema apresenta a mensagem MSG007.
FB.6. O ator confirma a mensagem.
.......
FB.9.   O sistema verifica que a data do pagamento é maior ou igual a data da emissão/contratação do fornecedor/prestador de serviço. [FA 3]

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.41

**Comment by marasb** [comment]
Defeito corrigido
