### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Erro na apresentação da mensagem MSG082

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#116]
Quando o usuário informa o valor do documento de pagamento diferente do valor total (seção detalhamento do gasto) o sistema apresenta a mensagem: MSG082
"O valor do documento de pagamento é diferente do valor total (seção detalhamento do gasto). Valor do Documento = R$ 50,00 Valor Total Pago = R$ 0,00."
Porém o valor total pago está sempre aparecendo 0,00.

Também sugiro que seja inserido um "Enter" antes do Valor do Documento e antes do Valor Total Pago, para ficar da seguinte forma:

O valor do documento de pagamento é diferente do valor total (seção detalhamento do gasto). 
Valor do Documento = R$ 50,00 
Valor Total Pago = R$ 0,00.

![erro_mensagem 082](https://cloud.githubusercontent.com/assets/6304414/2777793/8193fbb8-caea-11e3-812e-42dce7f6ba4d.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão2.0.43

**Comment by marasb** [comment]
Defeito corrigido.
