### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Erro no valor total pago

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#117]
O sistema está somando incorretamente o valor total pago, pois está considerando a soma de todos os documentos.
A soma do valor total pago deve ser a soma dos valores pagos daquele documento específico.

1) Realizar 1 pagamentos para um gasto X.
2) Pesquisar o registro do pagamento realizado.
3) Observar o valor do pagamento realizado.
4) Acionar o botão Incluir Registro de Pagamento.
5) Não incluir nenhum valor pago.
6) Observar que o sistema está apresentando o valor total pago já preenchido com o valores do outro documento.

![erro_ valor total pago 1](https://cloud.githubusercontent.com/assets/6304414/2778753/514cc272-caf5-11e3-9023-07f586d61475.png)
![erro_ valor total pago 2](https://cloud.githubusercontent.com/assets/6304414/2778755/54c7aa70-caf5-11e3-8551-698d5958d41a.png)

**Comment by rsantanam** [comment]
Mara, o <b>"valor total"</b>  é o somatório dos valores dos <b>pagamentos</b> para o <b>gasto</b> selecionado. Ao acionar o incluir estará adicionando um novo pagamento para o gasto.

**Comment by marasb** [comment]
Rogério,

De acordo com a regra de negócio RN83 em relação ao campo Valor Total:
"Valor Total: Este campo apresentará o resultado do somatório do campo Valor Pago de todos os fornecedores/prestadores de serviço exibidos na lista.
Valor Total = ∑(Valor Pago).
O sistema deverá apresentar o valor total atualizado à medida que o usuário informa o valor pago."

De acordo com o caso de uso, item descrição dos campos, está definido "Valor Total: Somatório do valor pago. Máscara: 0.000.000.000,00 "

Ou seja, de acordo com a regra esse campo é o somatório dos valores pagos exibidos na lista.

**Comment by jadossantos** [comment]
Stella,
O campo <b>Valor Total</b> é para exibir o somatório de todos os pagamentos <b>associados</b> ao Gasto em questão ou é para exibir o somatório de todos os pagamentos que estão sendo <b>exibidos na tela</b> no momento de inclusão/alteração?

**Comment by marasb** [comment]
Joel,

A Stella não está mais atuando nos projetos do TSE.
Porém ontem eu conversei com ela e fui informada que o valor total é o somatório dos valores da pagos exibidos na lista.
Ou seja, é o somatório dos valores pagos daquele documentos específico.

Segue o anexo da regra de negócio.

![erro_valor total](https://cloud.githubusercontent.com/assets/6304414/2789630/72850ce0-cbb0-11e3-86cf-8a7d8aec0402.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.46

**Comment by marasb** [comment]
defeito corrigido.
