### ISSUE TITLE
CDU_SPCA_026_Manter_Registro_do_Pagamento - Sistema não apresenta CPF/CNPJ na tela de pesquias de pagamento

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#118]
Na tela Pesquisa - Registro do pagamento o sistema não está apresentando o número do CPF/CNPJ na seção Identificação do Fornecedor/Prestador de Serviço.

![erro_ cpf-cnpj no apresentado na tela de pesquisa de pagamento](https://cloud.githubusercontent.com/assets/6304414/2781241/a64ef454-cb11-11e3-83fc-d88ec3d5cdde.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido.
