### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Data Invalida

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#119]
Verificar o comportamento do sistema, pois após informar uma data inválida o sistema emite a mensagem de alerta, mas não permite selecionar uma data válida através do calendário disponível conforme destacado na imagem anexa.

![datainvalida](https://cloud.githubusercontent.com/assets/6584772/2781660/554ce228-cb16-11e3-8b78-8ab3917e5774.png)

**Comment by jadossantos** [comment]
Item resolvido.
A solução implementada irá limpar o campo ao tentar alterar o valor do mesmo. Sendo que o mensagem já foi exibida.

**Comment by jmatil** [comment]
Testado e confirmada a correção conforme relato acima.
