### ISSUE TITLE
HU_SPCA_Identificar o adm do prestador de contas  - Erro ao agrupar as mensagens do prestador de contas

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#12]
As mensagens abaixo estão agrupadas por "Dados do Presidente", sendo que o correto é "Dados do Prestador de Contas":
-   Dados do Presidente
  -   - Partido não confere com a informação cadastrada para o número do CNPJ informado.
  -   - UF não confere com a informação cadastrada para o número do CNPJ informado.
  -   - Município/Zona não confere com a informação cadastrada para o número do CNPJ informado.
  -   - Período de Vigência não confere com a informação cadastrada para o número do CNPJ informado.

**Comment by flavioribeirom** [comment]
Liberado para teste

**Comment by marasb** [comment]
Defeito Corrigido.
