### ISSUE TITLE
CDU_SPCA_026_Manter_Registro_do_Pagamento - Erro nos hints da tela de pesquisa de pagamento

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#120]
Na tela Pesquisa - Registro do pagamento o sistema apresenta erro nos hints abaixo:
Botão Pesquisar está sendo apresentado "Pesquisar", sendo que o correto é "Pesquisar registro do pagamento".
Botão Incluir está sendo apresentado "Incluir", sendo que o correto é Incluir registro do pagamento.
Botão Excluir está sendo apresentado "Excluir", sendo que o correto é Excluir registro do pagamento
Botão Alterar está sendo apresentado "Alterar", sendo que o correto é Alterar registro do pagamento
Botão Detalhar está sendo apresentado "Detalhar", sendo que o correto é Detalhar registro do pagamento.

![erro_hint boto pesquisar](https://cloud.githubusercontent.com/assets/6304414/2781739/33216114-cb17-11e3-913b-560a79f149c5.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido.
