### ISSUE TITLE
CDU_SPCA_026_Manter_Registro_do_Pagamento - Erro na pesquisa de registro de pagamento

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#121]
Na tela de Pesquisa - Registro do pagamento o sistema está apresentando erro no resultado de pesquisa quando informado os campos "Número do Documento de Pagamento" e "Número do Lançamento" + qualquer operação.

**Comment by jadossantos** [comment]
Resolvido na versão 2.0.42.
Por favor, ao iniciar a aplicação executar o seguinte comando -> ctrl + F5

**Comment by marasb** [comment]
Defeito corrigido.
