### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Erro breadcrumb

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#122]
O breadcrumb  (caminho) está sendo apresentado incorreto na tela de aplicação de recurso: Você está em > Login > Selecionar Prestador de Contas > Home > Cadastro > registro.gasto.menu.aplicacao.recursos

![erro_menu](https://cloud.githubusercontent.com/assets/6304414/2790108/370267ec-cbb7-11e3-83ca-1af18563b998.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.45

**Comment by marasb** [comment]
Defeito corrigido.
