### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Erro no valor total pago está incorreto

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#123]
Na tela de cadastro de registro de gasto foi observado que o Valor total pago está incorreto, pois está dobrando o valor correto.
Ex.: Foram feitos dois pagamentos para o gasto de 500,00, ao acessar a tela de cadastro de gasto foi observado o valor total pago igual a 2.000,00.

![erro_valor total pago na tela de gasto](https://cloud.githubusercontent.com/assets/6304414/2790520/e731a8a8-cbbc-11e3-95a4-537273198def.png)
![erro_valor total pago na tela de gasto_1](https://cloud.githubusercontent.com/assets/6304414/2790523/ec35c4ce-cbbc-11e3-8581-0002e054bad0.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.47

**Comment by marasb** [comment]
Defeito corrigido.
