### ISSUE TITLE
CDU_SPCA_026_Manter_Registro_do_Pagamento - Mensagem não emitida

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#124]
Verificar o comportamento do sistema, pois ao "ALTERAR" informações e tentar simular o fluxo de exceção [1] o sistema não emitiu a mensagem de obrigatoriedade de preenchimento para os campos destacados na imagem, sendo emitida somente caso o campo "Valor do Documento de Pagamento" não estiver preenchido.

![preenchimento](https://cloud.githubusercontent.com/assets/6584772/2792544/42176bd8-cbd4-11e3-8512-c27f0ddc24aa.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.48

**Comment by jmatil** [comment]
Verificado a correção

![corrigido](https://cloud.githubusercontent.com/assets/6584772/2802930/d34ef0e8-cc93-11e3-9b0a-8ab743aa9c24.png)
