### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Mensagem MSG082 está incorreta.

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#125]
O sistema está apresentando a mensagem MSG082 (O valor do documento de pagamento é diferente do valor total (seção detalhamento do gasto). Valor do Documento = <valor do documento> Valor Total Pago = <∑ valor pago>.) mesmo quando o valor do documento de pagamento é igual ao valor total pago.

![erro_mensagem msg082 est incorreta](https://cloud.githubusercontent.com/assets/6304414/2792699/399f15a8-cbd6-11e3-843a-ee34a70ad67d.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.47

**Comment by marasb** [comment]
Defeito corrigido.
