### ISSUE TITLE
CDU_SPCA_026_Manter_Registro_do_Pagamento - Erro no tipo do campo Número de Lançamento

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#126]
Na tela de registro de pagamento (inclusão/alteração) o campo Número do Lançamento está aceitando apenas caracteres do tipo Numérico, porém o caso de uso define o tipo de caracteres Alfanumérico.

![erro_tipo campo nmero do lanamento](https://cloud.githubusercontent.com/assets/6304414/2800447/670c41a8-cc73-11e3-86ac-cb00a38b2fa2.png)

**Comment by jadossantos** [comment]
Resolvido na versão 2.0.51.

**Comment by marasb** [comment]
Defeito corrigido.
