### ISSUE TITLE
CDU_SPCA_026_Manter_Registro_do_Pagamento - O sistema apresenta as duas  janelas de  mensagens ao mesmo tempo (MSG007 e MSG089)

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#127]
Na tela de registro de pagamento (inclusão/alteração) quando o usuário informa a data do pagamento maior que a data atual o sistema apresenta as duas  janelas de  mensagens ao mesmo tempo (MSG007 e MSG089), sendo que a mensagem MSG007 aparece sobrepondo a MSG089.
O correto é o sistema apresentar uma mensagem de cada vez, primeiro apresenta a MSG007 e após confirmação apresentar a MSG089.

![erro_mensagens apresentando juntas](https://cloud.githubusercontent.com/assets/6304414/2800588/0051a4dc-cc76-11e3-9764-191a55ac4a3d.png)

**Comment by jadossantos** [comment]
Resolvido na versão 2.0.49.

**Comment by marasb** [comment]
defeito corrigido.
