### ISSUE TITLE
CDU_SPCA_026_Manter_Registro_do_Pagamento - Erro na apresentação da mensagem de obrigatoriedade quando o sistema apresenta a MSG082

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#128]
Na tela de registro de pagamento (inclusão/alteração) quando o usuário informa um valor de documento de pagamento diferente do valor total pago o sistema apresenta a mensagem MSG082, porém ao clicar em "OK" o sistema não apresenta as mensagens de obrigatoriedade dos campos não informados.

![erro_obrigatoriedade dos campos na tela de registro de pagamento](https://cloud.githubusercontent.com/assets/6304414/2800881/7c7ca058-cc7a-11e3-9806-371a59ca9099.png)

**Comment by jadossantos** [comment]
Resolvido na versão 2.0.50.

**Comment by marasb** [comment]
Defeito corrigido.
