### ISSUE TITLE
CDU_SPCA_026_Manter_Registro_do_Pagamento - Erro no perfil dos usuários Consulta e Operador

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#129]
Os usuário com perfil de consulta  e operador não tem acesso as funcionalidades de origem de recurso e aplicação de recurso.

Segue a descrição dos casos de uso em relação ao perfil dos usuários:

CDU_SPCA_024_Manter_Origem_de_Recurso
Os usuários do prestador de contas com perfil Administrador e Operador poderão pesquisar, incluir, editar, excluir e detalhar as informações da origem de recurso.
Os usuários do prestador de contas com perfil Consulta poderão apenas pesquisar e detalhar as informações da origem de recurso.

---

CDU_SPCA_025_Manter_Registro_do_Gasto
O ator com perfil Administrador e Operador poderá pesquisar, incluir ( ), editar ( ), excluir ( ) e detalhar ( ) as informações do registro do gasto.
O ator com perfil Consulta poderá apenas pesquisar e detalhar ( ) as informações do registro do gasto.
O sistema deve permitir que o ator navegue entre as abas “Gasto” e “Pagamento” sempre que ele quiser.

---

CDU_SPCA_026_Manter_Registro_do_Pagamento
O ator com perfil Administrador e Operador poderá pesquisar, incluir ( ), editar ( ), excluir ( ) e detalhar ( ) as informações do registro do pagamento.
O ator com perfil Consulta poderá apenas pesquisar e detalhar ( ) as informações do registro do pagamento.

**Comment by jadossantos** [comment]
Resolvido na versão 2.0.52.

**Comment by marasb** [comment]
Defeito Corrigido.
