### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Corrigir o tamanho do campo Nome/Razão Social

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#130]
Na tela de Registro do Gasto corrigir o tamanho do campo Nome/Razão Social para 70/300, conforme definido no caso de uso.

**Comment by jadossantos** [comment]
Resolvido na versão 2.0.52.

**Comment by marasb** [comment]
defeito corrigido.
