### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_ PrestadordeContas - Planilha do Plano de Contas

### ISSUE THREAD

**Issue by jadossantos** [islssa/SPCA#131]
Daniel,

Aonde obtenho a planilha <b>"PLANO DE CONTAS_ITERAÇÃO 4_Proposta"</b> que é referenciada na <b>RN089</b>?
Essa planilha será atualizada ou será fixa?

**Comment by dassuncao** [comment]
Joel,

A planilha foi disponibilizada no repositório, branch master. Será um dado fixo.

**Comment by rsantanam** [comment]
Daniel,

Existe um script de carga para o Banco de Dados da planilha enviada?
Caso não tenha poderia verificar a possibilidade da planilha estar no formato do exemplo abaixo?
![image](https://cloud.githubusercontent.com/assets/6524452/3473194/fc5984b8-02d4-11e4-80a6-164334bfad0f.png)

**Comment by dassuncao** [comment]
Rogério,
Não há script. Vou organizar a planilha conforme orientação descrita em exemplo e encaminhar a vocês.

**Comment by rsantanam** [comment]
Ok, estamos aguardando.
Obrigado.

**Comment by dassuncao** [comment]
Rogério,
A planilha foi ordenada e disponibilizada no repositório.

**Comment by rsantanam** [comment]
Ok Daniel.
