### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_ PrestadordeContas - Nenhum código resumido foi informado

### ISSUE THREAD

**Issue by rsantanam** [islssa/SPCA#132]
Daniel,

O campo código resumido deve ser preenchido em todos os planos que estiverem abertos para edição, não sendo possível gravar caso algum esteja vazio?
É isso que o fluxo de exceção FE.3 diz?

**Comment by dassuncao** [comment]
Rogério,

O campos "Código resumido" podem ser preenchidos ou não, a qualquer momento. Não é necessário preenchê-los totalmente para que se possa gravar a informação.
A FE3 diz respeito quando o usuário acionar o botão gravar sem ter realizado a ação de incluir ou editar algum código resumido. Essa exceção foi solicitada visando apresentar mensagem ao usuário quando houver o acionamento do botão gravar, sem que haja a inclusão ou edição de código resumido.
