### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_ PrestadordeContas - RAP 25

### ISSUE THREAD

**Issue by rsantanam** [islssa/SPCA#133]
Daniel,

No SPCA, por padrão, usamos o <b>Selecione</b> ao invés de <b>Todos</b>. Sendo assim acredito que a RAP25 poderia ser alterada para atender o exposto.

**Comment by dassuncao** [comment]
Boa tarde, 
Entendido a solicitação visando a padronização conforme demais apresentações, porém a opção foi definida pelo cliente, que segundo ele, seria a apresentação explícita de todos os registros do plano de contas. 
Por esse motivo, a opção "Todos" será mantida apenas nesse contexto, para as demais futuras elicitações, será mantido o padrão "Selecione".

**Comment by rsantanam** [comment]
Ok Daniel, já que foi uma solicitação do cliente implementaremos conforme definido.
Obrigado.
