### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_ PrestadordeContas - RN 089

### ISSUE THREAD

**Issue by rsantanam** [islssa/SPCA#134]
Daniel,

A RN 89 diz que <i> "o indicador de aceitação de Código Resumido = “Vazio” "</i> , estamos fazendo a modelagem da tabela e acho que seja mas intuitivo para que esta analisando o modelo de dados bem como quem implementa que a coluna seja preenchida com SIM ou NÃO ao invés de "Vazio" e "outra descrição". Dessa forma o modelo fica mais intuitivo.
Podemos adotar a sugestão?

**Comment by dassuncao** [comment]
Rogério,
Sim, a planilha do plano de contas e o documento de regras e mensagens foram atualizados no repositório conforme orientação.
