### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_ PrestadordeContas - Planilha Plano de Contas

### ISSUE THREAD

**Issue by rsantanam** [islssa/SPCA#135]
Daniel,

Identificamos alguns problemas referente a "Planilha de Plano de Contas" no que se refere a vinculação entre pais e filhos.

Segue um exemplo:
![image](https://cloud.githubusercontent.com/assets/6524452/3570665/9d10f2f2-0b53-11e4-9efb-24bffa752b64.png)

Poderia verificar o quanto antes, isso implica diretamente no desenvolvimento da funcionalidade.
Obs: Esse foi um exemplo mas podem haver outros casos.

**Comment by dassuncao** [comment]
Rogério,
A planilha será apresentada ao cliente, para que ele possa analisar e definir toda a ordenação e nomenclatura dos itens com mesmo código.

**Comment by dassuncao** [comment]
Rogério, 
A planilha foi revisada e ordenada. Em contato com o cliente, constatamos que houve um erro na apresentação do registro "Aluguéis Pagos Antecipadamente a Apropriar" que possuia o código 1.2.2.01.01.02. Agora está atribuído como: 1.2.2.01.02.02. 
O documento foi atualizado no repositório.

**Comment by jadossantos** [comment]
Daniel,

Identificamos um novo problema na planilha. O Planos de Contas com código igual <b>2.1.2</b> não tem pai, ou seja, não existe o código <b>2.1</b> nem <b>2</b>. Poderia revisar essas numerações?

Segue abaixo a imagem para exemplificar o problema:
![image](https://cloud.githubusercontent.com/assets/7116054/3586431/487bd300-0c30-11e4-97f7-45dabde5360a.png)

**Comment by dassuncao** [comment]
De acordo. Será analisado junto com o cliente

**Comment by dassuncao** [comment]
Senhores,
A planilha do plano de contas foi revisada e atualizada. O documento encontra-se disponível no repositório.
