### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_PrestadordeContas - Erro ao tentar cadatrar um novo usuário - IMPEDITIVO

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#136]
Foi realizada a Qualificação do Prestador de Contas e Identificação do Administrador, porém ao tentar realizar o cadastro do "Usuário Prestador de contas" utilizando os mesmos dados do administrador, o sistema apresenta a mensagem "O título de eleitor informado já está cadastrado para outro usuário.", porém nesse caso estamos tratando do mesmo usuário, ou seja, essa mensagem não deveria ser apresentada.
Sendo assim não está sendo possível acessar o sistema, visto que não estamos conseguindo cadastrar os usuários.

![erro1_erro impeditivo ao criar o usuario](https://cloud.githubusercontent.com/assets/6304414/3678329/5628c908-1299-11e4-907f-e88ff801d9e0.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido.
