### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_PrestadordeContas - Erro "could not extract ResultSet" ao acessar on plano de contas

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#137]
Ao acessar a funcionalidade "Plano de Contas" o sistema está apresentando a mensagem de erro "could not extract ResultSet".
Sendo assim não consigo executar nenhuma ação na funcionalidade.

![erro2_erro could not extract resultset](https://cloud.githubusercontent.com/assets/6304414/3687987/46b65fac-1330-11e4-8a43-5b6f3255f4bf.png)

**Comment by rsantanam** [comment]
Poderia passar o usuário e senha ?

**Comment by marasb** [comment]
Seguem os dados do usuário para acesso ao sistema:
CPF: 601.454.450-03
TE: 803285421066
USUÁRIO: JOÃO SILVA
SENHA: TEts!@1234

**Comment by jadossantos** [comment]
O problema foi resolvido.

**Comment by marasb** [comment]
Defeito corrigido.
