### ISSUE TITLE
[SPCA] Iteração 4 - Plano de Contas

### ISSUE THREAD

**Issue by dassuncao** [islssa/SPCA#138]
Prezados,
Após acesso e análise, encontrei 3 inconsistências:

1 - Ao acessar a tela do plano de contas, o sistema apresenta mensagem de erro "Could not extract ResultSet".
2 - A nomenclatura "Fundo Partidário" não é apresentada corretamente em lista.
3 - O plano de contas não apresenta nenhum resultado.

OBS: Testes efetuados no Mozilla Firefox, Google Chrome e IE.
![imagem_gh](https://cloud.githubusercontent.com/assets/8039491/3706335/5f92ec22-1428-11e4-8703-91153f6b724d.png)

**Comment by jadossantos** [comment]
Problema duplicado #137
