### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_PrestadordeContas - Erro na máscara do campo Código da Conta

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#139]
Login > Selecionar Prestador de Contas > Plano de Contas

O campo Código da Conta não está apresentando a máscara definida no caso de uso.
Este campo deve possuir a máscara "0.0.0.00.00.00.00".

![erro5_falta mscara no campo codigo da conta](https://cloud.githubusercontent.com/assets/6304414/3755505/d206acb6-1825-11e4-8818-f5155686b256.png)

**Comment by jadossantos** [comment]
Resolvido na nova implementação.

**Comment by marasb** [comment]
Defeito corrigido.
