### ISSUE TITLE
HU_SPCA_Alterar Endereco do Prestador - O sistema está excluindo os telefones cadastrados quando acionamos o comando "Excluir".

### ISSUE THREAD

**Issue by wesleyreis** [islssa/SPCA#14]
Trilha de navegação: Cadastro > Qualificação

Passo(s) para reproduzir:

P1 - Acionar o comando "Limpar".

Os telefones, já cadastrados, são excluídos quando realizamos o passo acima.

**Comment by AllanCruzRosa** [comment]
Wesley,
esse comportamento e para acontecer mesmo ,pois ao clicar no botão limpar você ira limpar todos os campos da tela inclusive a grid de telefone , esse comportamento pode ser visto também na tela de agente responsável.

**Comment by wesleyreis** [comment]
Allan,

Irei fechar a ocorrência.

Atenciosamente,

Wesley Reis.
