### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_PrestadordeContas - Erro na pesquisa do plano de contas

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#140]
A pesquisa do plano de contas está sendo realizada incorretamente, pois quando informamos algum parâmetro e acionamos o botão "Pesquisar" o sistema está apenas direcionando a tela para o item da pesquisa realizada. Sendo que o correto é que o sistema apresente apenas o resultado da pesquisa de acordo com o parâmetro informado, seguindo a regra abaixo:

"RAP26. Apresentação da lista do plano de contas
As contas devem ser apresentadas de acordo com sua estrutura hierárquica independente do parâmetro de pesquisa informado.
Caso seja informado o campo Código da Conta: O sistema deve apresentar todas as contas que possuem o código ou parte do código informado;
Caso seja informado o campo Descrição da Conta: O sistema deverá apresentar todas as contas que possuem a descrição ou parte da descrição informada;
Caso seja informado o campo Código Resumido: O sistema deve apresentar a conta que possui o código resumido informado."

**Comment by dassuncao** [comment]
Pessoal,

Encontrei um detalhe importante e que faltou a atualização descritiva para a RAP26 para o atendimento coerente na pesquisa e resultado de acordo com a filtragem.

Essa definição foi proposta, porém, para a apresentação em árvore, que estava prevista no início do levantamento de requisitos. Em árvore, seria coerente pois poderíamos apresentar vários registros da forma com que várias descrições possam ser apresentadas.

Sugiro pensarmos, se possível atualizar RAP26 para uma descrição coerente para a apresentação dos dados, como por exemplo, destaca-los:

"RAP26. Apresentação da lista do plano de contas
As contas devem ser apresentadas de acordo com sua estrutura hierárquica independente do parâmetro de pesquisa informado, com visualização da barra de rolagem, apresentando 30 linhas/registros por vez. Exemplo:
Se o usuário informar o parâmetro de pesquisa Código da Conta = 2.1.2, o sistema deve redirecionar o usuário ao resultado encontrado, destacando-o em amarelo, por exemplo:

<Apresentação da tela com o resultado em destaque e barra de rolagem>

Caso seja informado o campo Código da Conta: O sistema deve apresentar todas as contas que possuem o código ou parte do código informado destacados em amarelo;
Caso seja informado o campo Descrição da Conta: O sistema deverá apresentar todas as contas que possuem a descrição ou parte da descrição informada destacadas em amarelo;
Caso seja informado o campo Código Resumido: O sistema deve apresentar a conta que possui o código resumido informado destacanto a informação em amarelo;

Para a apresentação dos três cenários, o sistema deve redirecionar a visualização do usuário ao primeiro resultado encontrado." <Isso já ocorre>

**Comment by marasb** [comment]
Daniel, concordo com sua proposta acima.

**Comment by jadossantos** [comment]
A implementação inicial era como a Mara descreu acima, porém aconteceram algumas alterações na necessidade do cliente e iremos apresentar o resultado em forma de lista e com paginação.

**Comment by marasb** [comment]
Defeito corrigido.
