### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_PrestadordeContas - Erro na validação da exceção FE2

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#141]
Caminho: Selecionar Prestador de Contas > Plano de Contas
Usuário utilizado
CPF: 372.374.425-70
TE: 746588770418
Senha: TEts!@1234

Descrição: O sistema está permitindo gravar o mesmo código resumido para mais de uma conta.
Comportamento Esperado: Se for informado código resumido que já foi cadastrado para uma conta, o sistema deverá apresentar a mensagem MSG091 "O código resumido <Código resumido> já está cadastrado."

![erro_validao da exceo fe2](https://cloud.githubusercontent.com/assets/6304414/3763928/17629836-18aa-11e4-8903-1d406cf68b09.png)

**Comment by jadossantos** [comment]
Resolvido na nova implementação.

**Comment by marasb** [comment]
Defeito corrigido.
