### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_PrestadordeContas - Erro na apresentação da mensagem "Não existe registro para o parâmetro informado."

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#142]
Caminho: Selecionar Prestador de Contas > Plano de Contas
Usuário utilizado
CPF: 372.374.425-70
TE: 746588770418
Senha: TEts!@1234

Descrição: Após o usuário simular uma situação que apresente a mensagem "Não existe registro para o parâmetro informado.", o sistema continua apresentando sempre essa mensagem. Ou seja, a mensagem fica permanente na tela, mesmo após o usuário realizar outra pesquisa que retorne resultado.

![erro_mensagem permanece na tela](https://cloud.githubusercontent.com/assets/6304414/3764138/2a9d3520-18ad-11e4-9b84-355765a4580d.png)

**Comment by jadossantos** [comment]
Resolvido na nova implementação.

**Comment by marasb** [comment]
Defeito corrigido.
