### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_PrestadordeContas - Sistema nao grava código resumido que foi deletado

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#143]
Caminho: Selecionar Prestador de Contas > Plano de Contas
Usuário utilizado
CPF: 372.374.425-70
TE: 746588770418
Senha: TEts!@1234

Descrição: Quando o usuário apaga um código resumido que foi cadastrado anteriormente e aciona o botão "Gravar", o sistema apresenta a mensagem para confirmar a operação, porém quando o usuário confirma a mensagem o sistema não apresenta a mensagem "Operação realizada com sucesso" e também não grava a alteração realizada.

DÚVIDA: O usuário pode apagar um código resumido que foi cadastrado para uma conta? Se sim, o sistema não está gravando essa ação.

![erro_sistema no est gravando as alteraes dos codigos resumidos](https://cloud.githubusercontent.com/assets/6304414/3764418/fcf581fa-18b0-11e4-9238-683ef988c3f5.png)

**Comment by jadossantos** [comment]
Resolvido na nova implementação.

**Comment by marasb** [comment]
Defeito corrigido.
