### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_PrestadordeContas - Sistema não está apresentando toda as informações do plano de contas

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#144]
Caminho: Selecionar Prestador de Contas > Plano de Contas
Usuário utilizado
CPF: 372.374.425-70
TE: 746588770418
Senha: TEts!@1234

Descrição: O sistema não está apresentando todas as informações do Plano de Contas. Pois o último item apresentado do plano de contas é  "2.3. PATRIMÔNIO LÍQUIDO".
Comportamento esperado: De acordo com o caso de uso, item 8 Observações, "É necessário apresentar todo o plano de contas no acesso ao menu correspondente, mesmo que a informação seja extensa e o sistema demande tempo maior no carregamento dos dados.".

![erro_sistema nao apresenta todo o plano de contas](https://cloud.githubusercontent.com/assets/6304414/3764473/9d9ad600-18b1-11e4-9a2c-0bb59f7cc888.png)

**Comment by jadossantos** [comment]
Mara,
A tabela apresentará 1012 registros, porém o servidor JBOSS não esta suportando tratar todos os registros de uma só vez. Um paliativo foi limitar o script de inserção em 500 registros até solucionar tal problema.
A nova implementação apresentará os registros com paginação. Assim que concluirmos tal implementação, iremos executar o script completo.

**Comment by marasb** [comment]
Defeito corrigido.
