### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_PrestadordeContas - Usuário com perfil "Consulta" possui permissão para edição do plano de contas.

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#145]
Caminho: Selecionar Prestador de Contas > Plano de Contas
Usuário utilizado
Nome: CONSULTA
CPF: 567.536.320-34
Título de eleitor: 376166710612
Senha: TEts!@1234

Descrição: Foi criado um usuário com perfil "Consulta", porém o mesmo possui permissão para edição do plano de contas.

Comportamento esperado: Os usuários do prestador de contas com perfil Consulta poderão pesquisar e apenas visualizar os dados do plano de contas. Para este perfil, todos os campos editáveis e o botão “Gravar” devem ser apresentados, porém desabilitados.

**Comment by jadossantos** [comment]
Resolvido na nova implementação.

**Comment by marasb** [comment]
Defeito corrigido.
