### ISSUE TITLE
HU_SPCA_Identificar o administrador do prestador de contas no SPCA-Cadastro - Sistema nao apresenta MSG093 para identificação do administrador

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#146]
Caminho: Qualificação do Prestador de Contas e Identificação do Administrador

Ao tentar identificar um administrador, informando um Titulo de eleitor já cadastrado para outra pessoa, o sistema não está apresentando a mensagem MSG093 "O título de eleitor informado já está cadastrado para outro usuário".
Quando acionamos o botão "Gravar" a tela permanece estática, ou seja, não acontece nada.
A mensagem só está sendo apresentada para o presidente.

Comportamento esperado: "•    Caso seja informado um número de título de eleitor para o presidente ou administrador que já está cadastrado para outra pessoa, o sistema deve apresentar a mensagem MSG093. Para este caso, o sistema não deve prosseguir com a operação."

![erro_mensagem 93 nao esta sendo apresentada](https://cloud.githubusercontent.com/assets/6304414/3765851/395f9546-18bf-11e4-920b-7a201d8e00ff.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido.
