### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_PrestadordeContas - Erro na apresentação dos caracteres especiais

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#147]
A tabela de contas apresenta erro nos caracteres especiais.
Exemplo: 
1.1.1.01.03. APLICAÃ¿Ã¿ES FINANCEIRAS
1.1.1.02.02.01. TRANSFERÃ¿NCIAS DO FUNDO PARTIDÃRIO A RECEBER
1.1.1.02.02.01.01. DireÃ§Ã£o Nacional  
1.1.1.02.02.01.02. DireÃ§Ã£o Estadual  
1.1.1.02.02.01.03. DireÃ§Ã£o Municipal

![erro_caracteres especiais](https://cloud.githubusercontent.com/assets/6304414/3828012/a4e6c100-1d73-11e4-9059-a88dc06338e8.png)

**Comment by jadossantos** [comment]
O problema foi na execução dos scripts de carga.

**Comment by marasb** [comment]
Defeito corrigido.
