### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_PrestadordeContas - Erro na gravação da alteração do código resumido.

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#148]
Foi indentificado erro ao tentar alterar um registro sem atualizar a página "Plano de Contas".
Seguem os passos para simulação do erro:

Acessar a página "Plano de Contas".
1. Inserir um código resumido em uma conta.
2. Acionar o botão gravar.
3. Verificar que o sistema grava o código resumido com sucesso.
4. Sem atualizar a página, deletar o código resumido cadastrado anteriormente.
5. Acionar o botão gravar.
6. ERRO 1: Verificar que o sistema não apaga a mensagem "Operação realizada com sucesso" e já apresenta a mensagem de confirmação "Confirma a operação". 
Comportamento esperado (ERRO1): Quando o usuário aciona o botão "Gravar", acredito que o sistema tenha que apagar a mensagem antiga e apresentar a mensagem nova.
7. Confirmar a operação.
8. ERRO 2: O sistema apresenta a mensagem "Nenhum código foi inserido ou alterado".
Comportamento Esperado (ERRO 2):  O sistema deveria realizar a alteração, visto que o código resumido foi deletado. Esse erro só está acontecendo quando o usuário realiza a alteração sem atualizar a página. Ou seja, se o usuário sair da funcionalidade e entrar novamente, ele conseguirá realizar a alteração corretamente.

**Comment by jadossantos** [comment]
ERRO 1 não procede, pois a mensagem só será atualizada após a conclusão do evento do clique do botão. Nesse caso a mensagem é  a mesma.

ERRO 2 foi resolvido.

**Comment by marasb** [comment]
Defeito corrigido.
