### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_PrestadordeContas - Sistema não permite excluir dois códigos resumidos de uma única vez

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#149]
Foram apagados 3 códigos resumidos, porém ao acionar o botão "Gravar" o sistema não realiza nenhuma ação. Ou seja, o sistema só está apaga o registro caso o usuário grave uma exclusão por vez.
Comportamento esperado: O sistema deverá apagar mais de 1 código resumido da mesma página de uma única vez..

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido.
