### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_PrestadordeContas - Faltam 4 registros no plano de contas

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#150]
A tabela "PLANO DE CONTAS_ITERACAO 4_Proposta" possui 1012 registros de contas, porém na aplicação está sendo apresentado 1008 registros.
Seguem os 4 itens que estão faltando na tabela: 1.1.1.01.02.01., 1.1.1.01.03.01., 1.1.1.01.03.02. e 1.1.1.02.01.01..

![erro_registros faltando na tabela plano de contas](https://cloud.githubusercontent.com/assets/6304414/3841822/57daa8ea-1e31-11e4-862b-bf571689de78.png)

**Comment by jadossantos** [comment]
Mara,
Os registros estão disponíveis e não consegui simular tal problema.

![image](https://cloud.githubusercontent.com/assets/7116054/3842922/81600ea8-1e3b-11e4-984f-a108c6580ac0.png)

**Comment by jadossantos** [comment]
Mara,

Consegui simular o problema com outro prestador de contas.

**Comment by marasb** [comment]
Defeito corrigido.
