### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_PrestadordeContas - Registros classificados como "FIXO PARA AMBOS" não estão sendo apresentados 

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#151]
Os códigos abaixo, classificados como "FIXO PARA AMBOS" na planilha "PLANO DE CONTAS_ITERACAO 4_Proposta", não estão sendo apresentados quando selecionamos o parâmetro "Fundo partidário" ou "Outros Recursos" no campo Tipo.
1.1.  ATIVO CIRCULANTE       FIXO PARA AMBOS
1.2.  ATIVO NÃO CIRCULANTE   FIXO PARA AMBOS
2.1.  PASSIVO CIRCULANTE     FIXO PARA AMBOS
2.2.  PASSIVO NÃO CIRCULANTE FIXO PARA AMBOS
2.3.  PATRIMÔNIO LÍQUIDO     FIXO PARA AMBOS
3.1.  DESPESAS OPERACIONAIS  FIXO PARA AMBOS
3.2.  OUTRAS DESPESAS        FIXO PARA AMBOS
3.2.1.PERDA NA ALIENAÇÃO DE BENS DE USO FIXO PARA AMBOS
4.1.  RECEITAS OPERACIONAIS  FIXO PARA AMBOS

DÚVIDA: Esses itens devem ser apresentados quando selecionamos os parâmetros "Fundo partidário" ou "Outros Recursos" no campo tipo???

![erro_registros fixo para ambos estao faltando](https://cloud.githubusercontent.com/assets/6304414/3842103/453262c0-1e34-11e4-841d-9c4d04a0a5d8.png)

**Comment by jadossantos** [comment]
Resolvido com uma correção na consulta.

**Comment by marasb** [comment]
Defeito corrigido.
