### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_PrestadordeContas - Caractere "¿" apresentado incorretamente

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#153]
As contas abaixo estão sendo apresentadas com o caractere "¿" no lugar do " - ".

2.3.1. PATRIMÔNIO SOCIAL ¿ FUNDO PARTIDÁRIO  
2.3.1.01. FUNDO PATRIMONIAL ¿ FUNDO PARTIDÁRIO  
2.3.1.01.01. FUNDO PATRIMONIAL ¿ FUNDO PARTIDÁRIO
2.3.2. PATRIMÔNIO SOCIAL ¿ OUTROS RECURSOS  
2.3.2.01. FUNDO PATRIMONIAL ¿ OUTROS RECURSOS  
2.3.2.01.01. FUNDO PATRIMONIAL ¿ OUTROS RECURSOS
3.2.1.01. PERDA NA ALIENAÇÃO DE BENS DE USO ¿ FUNDO PARTIDÁRIO  
3.2.1.02. PERDA NA ALIENAÇÃO DE BENS DE USO ¿ OUTROS RECURSOS
4.1.1.02. RECEITAS DE SOBRAS DE CAMPANHA - FINANCEIRAS - FUNDO PARTIDÁRIO ¿ A PARTIR DO PLEITO DE 2010
4.1.1.03. RECEITAS DE SOBRAS DE CAMPANHA - BENS PERMANENTES ESTIMÁVEIS - FUNDO PARTIDÁRIO ¿ A PARTIR DO PLEITO DE 2010
4.1.1.03.02. Sobras de Campanha ¿ Comitês 
4.1.1.03.03. Sobras de Campanha ¿ Partidos Políticos
4.1.2.06. RECEITAS DE SOBRAS DE CAMPANHA - FINANCEIRAS - OUTROS RECURSOS ¿ A PARTIR DO PLEITO DE 2010
4.1.2.06.02. Sobras de Campanha ¿ Comitês 
4.1.2.06.03. Sobras de Campanha ¿ Partidos Políticos  
4.1.2.07. RECEITAS DE SOBRAS DE CAMPANHA - BENS PERMANENTES ESTIMÁVEIS - OUTROS RECURSOS ¿ A PARTIR DO PLEITO DE 2010
4.1.2.07.02. Sobras de Campanha ¿ Comitês 
4.1.2.07.03. Sobras de Campanha ¿ Partidos Políticos
4.2.1.01. GANHO NA ALIENAÇÃO DE BENS DE USO ¿ FUNDO PARTIDÁRIO  
4.2.1.02. GANHO NA ALIENAÇÃO DE BENS DE USO ¿ OUTROS RECURSOS

**Comment by jadossantos** [comment]
É o mesmo problema da #147

**Comment by marasb** [comment]
Então vou reabrir o primeiro erro. Pois agora só aconteceu em alguns itens.

**Comment by marasb** [comment]
O bug foi resolvido.
