### ISSUE TITLE
CDU_SPCA_028_Associar_PlanodeContas_Prestador_de_Contas MENSAGENS

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#155]
Prezados
Verificar o comportamento do sistema na seguinte simulação:
1º Realizar o cadastro de um código resumido
2º Realizar a pesquisa inserindo no campo "código resumido" o mesmo código utilizado no cadastro.
4º Limpar o campo que contenha o código utilizado "No resultado da pesquisa" e acionar a opção "Gravar"
5º Verificar as mensagens emitidas pelo sistema: "Não existe registro para o parâmetro informado." & "Operação realizada com sucesso."
OBS: Ao acionar a opção "Gravar" o sistema parece que interpretou esta ação juntamente com a opção de pesquisa. Segue imagem do resultado obtido após executar esses passos.

![mensagem](https://cloud.githubusercontent.com/assets/6584772/3857852/1a7a4172-1f08-11e4-85d4-98226274b1ac.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Foi verificado que o item foi corrigido
