### ISSUE TITLE
HU_SPCA_Identificar o administrador do prestador de contas no SPCA-Cadastro / Data

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#156]
Prezados
Verificar o comportamento do sistema, pois a mensagem de preenchimento obrigatório não foi contemplada para os campos "Data". Apenas emitiu a mensagem de data inválida. Já ao preencher os campos com "Data" inválida juntamente com os outros campos, os sistema não emite a mensagem de "Data inválida". 

![data](https://cloud.githubusercontent.com/assets/6584772/3876049/660168c6-2158-11e4-86e7-97cc7af4bf32.png)

![data1](https://cloud.githubusercontent.com/assets/6584772/3876106/cf613be8-2158-11e4-9537-a4a75598734f.png)

**Comment by jadossantos** [comment]
Não consegui simular o problema.

**Comment by jmatil** [comment]
Na tentativa de simular o erro foi verificado a não persistência da ação citada acima.
