### ISSUE TITLE
HU_SPCA_Incluir usuario do prestador de contas no SPCA-Cadastro / Título já cadastrado

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#158]
Prezados
Favor verificar a mensagem emitida pelo sistema, pois ao disponibilizar apenas o título de eleitor pertencente a um Usuário Prestador de contas já cadastrado o sistema não emitiu a mensagem conforme relatado na documentação. Seguem imagens para as devidas comparações.

Descrição
![doc1](https://cloud.githubusercontent.com/assets/6584772/3905272/793087cc-22e5-11e4-9568-3de35d6b1314.PNG)

Mensagem
![msg93](https://cloud.githubusercontent.com/assets/6584772/3905273/7f8419ea-22e5-11e4-8ac5-be9923e4e341.PNG)

Sistema
![sistema](https://cloud.githubusercontent.com/assets/6584772/3905278/8b0c1434-22e5-11e4-979b-ab36d62af26d.PNG)

**Comment by jadossantos** [comment]
Jailson,

Fizemos a correção e a validação ficou assim:

![image](https://cloud.githubusercontent.com/assets/7116054/3907100/b3066f1c-22f8-11e4-8c51-5010f720aac9.png)

Por causa da regra:

O sistema não poderá gravar uma pessoa indicada a ser usuário do SPCA com o mesmo número de CPF ou número de título de eleitor que já esteja cadastrado. Caso isto aconteça, o sistema apresentará a mensagem MSG044.

**Comment by jmatil** [comment]
Verificado a alteração. Evidência fechada
