### ISSUE TITLE
[Iteração 5] - CDU_SPCA_032_Gerar_Demonstrativo_de_Recursos_Recebidos_do_Fundo_Partidario - Campo PROCEDÊNCIA (Descrição do partido político autenticado)

### ISSUE THREAD

**Issue by rsantanam** [islssa/SPCA#159]
Daniel,

Qual o label a ser exibida para o campo <b>PROCEDÊNCIA (Descrição do partido político autenticado)</b> ? Não consegui visualiza-lo no <b>PT2.Demosntrativo em Tela</b>.

**Comment by dassuncao** [comment]
Oi, Rogério.

Certo, sobre a (Descrição do partido autenticado), a informação também deve ser adquirida de forma semelhante à descrição inserida em minha resposta ao "https://github.com/islssa/SPCA/issues/160".
No exemplo descrito em protótipo, temos a apresentação do PEN-BR. Isso significa que o partido PEN-BR, gerou o demonstrativo.
Se por acaso tivéssemos realizado a autenticação com um usuário prestador de contas do PT-BA-Salvador, significaria que o exemplo seria a apresentação do demonstrativo referente ao PT-BA-Salvador.

**Comment by dassuncao** [comment]
Rogério,

A informação deve ser a do partido logado, por exemplo:

Se estou logado com o PEN-BR, significa que seria o partido deve ser apresentado na label, abaixo da informação do TSE. (Conforme caso de uso e seguindo a RN69)

Se estou logado com o PEN-RJ/Macaé, a informação seria apresentada nessa linha, veja exemplo abaixo:
![sem titulo](https://cloud.githubusercontent.com/assets/8039491/5961305/e7e4874c-a7c2-11e4-8b52-5860215f814f.png)

**Comment by rsantanam** [comment]
Ok.
