### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Erro na validação dos campos CPF/CNPJ

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#16]
Quando o sistema apresenta alguma exceção de CPF ou CNPJ (CPF ou CNPJ inválido, CPF ou CNPJ com menos de 11 ou 14 dígitos), e logo após o usuário alterar a origem do recurso e informar um número de CPF ou CNPJ, o sistema apresenta sempre a última mensagem da exceção gerada.

Passo a passo:
1) Na tela Origem de Recurso, selecionar o campo Origem do Recurso: Pessoa Física.
2) No campo CPF informar um número de CPF inválido.
3) Acionar o botão Gravar.
4) O sistema apresenta a mensagem "O CPF é inválido.", corretamente.
5) Alterar o campo Origem de Recurso para: Pessoa Jurídica.
6) No campo CNPJ informar um número de CNPJ inválido, ou CNPJ correto, ou CNPJ com menos de 14 dígitos.
7) Acionar o botão Gravar.
8) O sistema sempre apresenta a mensagem " O CPF é inválido." .

![erro_validao cpf-cnpj](https://cloud.githubusercontent.com/assets/6304414/2550618/da0f014a-b684-11e3-81f1-ba2dd972134d.png)

**Comment by rsantanam** [comment]
Resolvido.
Obs: Versão: 2.0.4

**Comment by marasb** [comment]
O defeito foi resolvido na versão Versão: 2.0.4.
