### ISSUE TITLE
[Iteração 5] - CDU_SPCA_032_Gerar_Demonstrativo_de_Recursos_Recebidos_do_Fundo_Partidario - RAP 70

### ISSUE THREAD

**Issue by rsantanam** [islssa/SPCA#160]
Daniel,

A RAP 70 diz que deve apresentar a sigla, uf e municipio do partido, porém as informações de UF e Municipio não são obrigatórias. Caso não tenha essas informações como deve-se apresentar a informação?

**Comment by dassuncao** [comment]
Olá, Rogério.

A RAP70, é apresentada, para que possamos distinguir em qual etapa/momento serão apresentadas as informações particulares que estão relacionadas ao partido autenticado. A informação deve ser obtida de acordo com os dados da autenticação do usuário.
Observe que no item 3 do caso de uso, temos a seguinte informação: 
"Este caso de uso descreve a funcionalidade que permite ao usuário, gerar e detalhar o demonstrativo com a relação de recursos recebidos do fundo partidário. O resultado do demonstrativo deve apresentar informações relacionadas à prestação de contas a qual o usuário está associado, autenticado, e somente em referência ao exercício correspondente."

**Comment by rsantanam** [comment]
Ok Daniel.
