### ISSUE TITLE
[Iteração 5] - CDU_SPCA_032_Gerar_Demonstrativo_de_Recursos_Recebidos_do_Fundo_Partidario - RAP 63

### ISSUE THREAD

**Issue by rsantanam** [islssa/SPCA#161]
Daniel,

A RAP 63 esta sendo referenciada na <b>PT2. Demonstrativo de tela<b> nos campos referentes a informações bancárias. Esta correto?

**Comment by dassuncao** [comment]
Olá, Rogério.

Sim, note que o demonstrativo poderá apresentar resultados referentes a mais de um banco, por isso a RAP63 é apresentada.

Se por exemplo o resultado do demonstrativo apresentar dois bancos, o documento deve separar as informações condizentes a cada um dos lançamentos realizados para cada banco, seria descritivamente parecido com o exemplo abaixo:
<Dados do demonstrativo>
<Dados do partido>

<Dados bancários 1>
<Apresentação do resultado em Grid>

<Dados bancários 2>
<Apresentação do resultado em Grid>

**Comment by rsantanam** [comment]
Ok Daniel, ficou claro apesar da imagem não ter sido anexada.
