### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Campo Nota Explicativa

### ISSUE THREAD

**Issue by jadossantos** [islssa/SPCA#163]
Daniel,

O campo <b>Nota Explicativa</b> é um campo texto ou uma combo exibindo os registros do CDU_SPCA_029_Manter_Nota_Explicativa?

**Comment by dassuncao** [comment]
Campo texto. Não há relacionamento desse campo com a funcionalidade proposta em CDU029.

**Comment by jadossantos** [comment]
Ok.
