### ISSUE TITLE
[Iteração - 5] CDU_SPCA_029_Manter_Nota_Explicativa - Campo número nota explicativa

### ISSUE THREAD

**Issue by rsantanam** [islssa/SPCA#164]
Daniel,

Gostaria de saber se existe a possibilidade do campo <b>Numero da Nota Explicativa</b>:
![image](https://cloud.githubusercontent.com/assets/6524452/6158650/4d80ec72-b22b-11e4-813b-a43ad90da08f.png)

... que é gerado automaticamente, ser removido da tela neste momento, pois isso acarretará um problema de concorrência. Caso dois(ou mais) usuários acessem ao mesmo tempo a tela todos teriam o mesmo <b>Numero da Nota Explicativa</b> na tela e na hora da persistência acabaria ocorrendo uma violação de integridade no banco.

<b>\* Sugestão</b>
Nesses casos de geração de informação incremental o ideal é que a mesma seja gerada no momento da inserção e depois exibi-la para o usuário. Poderíamos exibir na mensagem de confirmação do registro salvo:
![image](https://cloud.githubusercontent.com/assets/6524452/6158909/047719ea-b22e-11e4-9d04-287c12aaf6b6.png)

ou num popup : 
![image](https://cloud.githubusercontent.com/assets/6524452/6158974/be152734-b22e-11e4-87ce-1e712d594d04.png)

  O que acha?

**Comment by dassuncao** [comment]
Rogério, estou de acordo.
O caso de uso 029 e o documento RMG foram alterados para melhor atendimento à essa requisição, por gentileza verificar a atualização no repositório.

**Comment by rsantanam** [comment]
Ok Daniel.
Obrigado.
