### ISSUE TITLE
HU_SPCA_Incluir Agente Responsavel - Cep inválido

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#165]
Quais itens (campos) estão sendo associados para validação do campo CEP? Tem alguma relação com a RN18 - Tabela de CEP?
![1](https://cloud.githubusercontent.com/assets/6584772/7182263/8980f28a-e426-11e4-8dd8-d5c0a2ce108e.png)

**Comment by jadossantos** [comment]
O CEP é validado pelo sistema através de uma carga que foi passada pelo TSE. Essa carga trabalha com sistema de faixas (inicial e final) e caso não exista esse valor na tabela o CEP será inválido.

**Comment by jmatil** [comment]
Item corrigido
