### ISSUE TITLE
CDU_SPCA_028_Associar_PlanoDeContas_PrestadorDeContas - Mensagem

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#167]
Verificar a mensagem enviada na tela e a solicitada no caso de uso

![3](https://cloud.githubusercontent.com/assets/6584772/7188822/d1719f3e-e450-11e4-8f29-0bbf7935542f.png)

**Comment by jadossantos** [comment]
A validações dos fluxos de exceções acontecerão de forma individual e caso seja identificado algum inconsistência a mensagem será apresentada para o usuário.

**Comment by jmatil** [comment]
Compreendido
