### ISSUE TITLE
HU_SPCA_Incluir Agente Responsavel - Mensagem 32

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#168]
Verificar a necessidade de inclusão ou não da palavra "Confirmar" na documentação de regra de mensagem
![4](https://cloud.githubusercontent.com/assets/6584772/7202938/3e5c2212-e4ed-11e4-985f-997021ad0d05.png)

**Comment by dassuncao** [comment]
MSG032 recebeu um acréscimo após o ponto para evidenciar a pergunta, conforme rescrito em Histórias de usuário correspondente ao agente responsável. O trecho descrito foi: "Deseja prosseguir?"

Atualização evidenciada em documento RMG_SPCA dispinível na pasta SM001_Iteracao_05 da branch master do projeto.

**Comment by jadossantos** [comment]
A mensagem foi alterada no sistema.

**Comment by jmatil** [comment]
Confirmado
