### ISSUE TITLE
HU_SPCA_Alterar Contas Bancárias - Origem de Recurso

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SPCA#169]
Prezados,

Conforme tela em anexo, após realizar o cadastro em [ Origem de Recurso ] e quando acessa o a opção "Gravar" o sistema não grava os dados, impossibilitando de apresentar a MSG011.

![1](https://cloud.githubusercontent.com/assets/9218077/7203169/1cbf954c-e4ef-11e4-8cf0-3c0ea034c348.jpg)

**Comment by rsantanam** [comment]
O cadastro foi realizado na tela de Origem de Recurso?

**Comment by kleiberfaria** [comment]
item já verificado !
