### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Alterar tamanho do campo Nome/Razão Social

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#17]
Na tela Origem de Recurso, sugiro que aumente o campo "Nome/Razão Social"  para ficar proporcional a quantidade de caracteres digitados (70)  e para que seja possível o usuário visualizar de forma completa o nome digitado.
Para manter o padrão do sistema, pode ser observado o campo Nome na tela Agente Responsável.
Segue em anexo a comparação.
![melhoria_tamanho do campo nome-razo social](https://cloud.githubusercontent.com/assets/6304414/2550825/8e6e77e0-b687-11e3-883a-056e070e15ec.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão: 2.0.4

**Comment by marasb** [comment]
Melhoria atendida.
