### ISSUE TITLE
HU_SPCA_Incluir Agente Responsavel - Botão "Gravar"

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#171]
Após simular uma excessão de campos considerados obrigatórios o sistema desativou o botão grava para que pudesse ser simulado a mensagem de Título de Eleitor Inválido. 

![6](https://cloud.githubusercontent.com/assets/6584772/7204026/831cad88-e4f5-11e4-8066-08e9f39b294f.png)

**Comment by jadossantos** [comment]
Não consegui simular o problema.

**Comment by jmatil** [comment]
Ação não está ocorrendo mais
