### ISSUE TITLE
HU_SPCA_Pesquisar Contas Bancárias - Filtrar

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SPCA#172]
Prezados,
Conforme tela em anexo, o campo [ Filtrar ] está permitindo mais de "30" caracteres. De acordo com o HU_Pesquisar Contas Bancárias o tamanho é "30".

![2](https://cloud.githubusercontent.com/assets/9218077/7209945/c61575e2-e523-11e4-99d7-55c787e08dac.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
