### ISSUE TITLE
HU_SPCA_Incluir Agente Responsavel - Cpf Inválido

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#173]
Verificar o validador de CPF após realizar um cadastro já excluído pelo ator, pois foi inserido o cadastro, o sistema puxou o nome do Agente Responsável, mas a mensagem de CPF Inválido foi emitida.

![7](https://cloud.githubusercontent.com/assets/6584772/7230191/e5254000-e741-11e4-972d-6d7b854d13af.png)

**Comment by jadossantos** [comment]
O título está mencionando o CDU <b>HU_SPCA_Pesquisar Contas Bancárias</b>, mas o problema é no <b>Agente responsável</b>. Favor corrigir.

**Comment by jmatil** [comment]
Corrigido
