### ISSUE TITLE
CDU SPCA 024 Manter Origem de Recurso - RAP 35

### ISSUE THREAD

**Issue by rsantanam** [islssa/SPCA#174]
Mônica,

Na RAP35 a <b>"Obs: 6"</b> fala sobre a exibição dos campos “Eleição” ou “Eleição Suplementar”, porém não identifiquei aonde estão definidos esses campos(tamanho, tipo e etc).

Poderia ajudar?

**Comment by monicaleite** [comment]
Daniel, 

Verifica essa pendência por favor.

**Comment by dassuncao** [comment]
O campo "Eleição" deve apresentar lista conforme descrito em RAP40.
Acréscimo evidenciado em RAP40:
O campo “Ano”, que diz respeito ao ano da eleição suplementar, deve identificar e permitir o preenchimento do ano 2010 em diante.

Novo trecho acrescentado:(Tamanho do campo deve a permitir a inclusão de até 4 caracteres obrigatórios do tipo numérico). 

OBS: É possível incluir 0001, por exemplo, porém o sistema deve acionar a FE16 do CDU024.

Atualização evidenciada em documento RMG_SPCA dispinível na pasta SM001_Iteracao_05 da brach master do projeto.

**Comment by rsantanam** [comment]
Ok.
