### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Validação de obrigatoriedade do campo Título de eleitor

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#18]
O sistema não está realizando validação do campo Título de eleitor quanto ao preenchimento obrigatório.
Não foi informando o campo título de eleitor e acionado o botão gravar, porém o sistema não apresentou a mensagem MSG005.
![erro_validao ttulo de eleitor - preenchimento obrigatrio](https://cloud.githubusercontent.com/assets/6304414/2552819/4f442d82-b69e-11e3-87ee-25037d38fb56.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.5

**Comment by marasb** [comment]
Defeito corrigido. Versão 2.0.12
