### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Sistema não está validando o campo título de eleitor quando informando menos de 12 posições.

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#19]
O sistema não está realizando validação do campo Título de eleitor quando o usuário informa menos de 12 posições.
Foi informado um número de título de eleitor com menos de 12 posições e acionado o botão gravar, porém o sistema não apresentou a mensagem MSG026. Indo contra o caso de uso, FE 13. Título de eleitor com menos de 12 posições.
![erro_validao ttulo de eleitor com menos de 12 posies](https://cloud.githubusercontent.com/assets/6304414/2552887/0abbe3c0-b69f-11e3-877b-1e1a54fa61c1.png)

**Comment by rsantanam** [comment]
Resolvido, com a correção do bug 18
Versão 2.0.5

**Comment by marasb** [comment]
Defeito corrigido. Versão 2.0.12
