### ISSUE TITLE
 CDU SPCA 034 Gerar Demonstrativo de Contribuições Recebidas

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#198]
Verificar a mensagem emitida para data inválida. Está contrária à exigida na documentação
![34](https://cloud.githubusercontent.com/assets/6584772/8283135/c6568056-18cb-11e5-9b01-251bd84e1fb2.PNG)

**Comment by rsantanam** [comment]
Corrigido.

**Comment by jmatil** [comment]
Correção confirmada
