### ISSUE TITLE
CDU SPCA 032 Gerar Demonstrativo de Recursos Recebidos do Fundo Partidário

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SPCA#199]
Prezado,
Conforme tela em anexo, ao deixar o campo "período" em branco e acionar a opção "Gerar" a aplicação não exibe nenhuma mensagem somente quando deixa preenchido um campo.

![1](https://cloud.githubusercontent.com/assets/9218077/8314450/09bf978e-19c0-11e5-9abb-5d6eed2e06a4.png)

**Comment by rsantanam** [comment]
O campo período não é obrigatório, por isso não é exibido mensagem.

**Comment by kleiberfaria** [comment]
Conforme documentação o campo "Período" não é obrigatório para essa funcionalidade.
