### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Sistema não está validando o campo título de eleitor inválido

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#20]
O sistema não está realizando validação do campo Título de eleitor quando o usuário informa um número de título inválido.
Foi informado um número de título de eleitor inválido e acionado o botão gravar, porém o sistema não apresentou a mensagem MSG021. Indo contra o caso de uso, FE 12.  Título de eleitor inválido.
![erro_validao ttulo de eleitor invlido](https://cloud.githubusercontent.com/assets/6304414/2552942/a079c36e-b69f-11e3-8697-ea0adfffd3d4.png)

**Comment by rsantanam** [comment]
Resolvido, com a correção do bug 18
Versão 2.0.5

**Comment by marasb** [comment]
Defeito corrigido. Versão 2.0.12
