### ISSUE TITLE
CDU SPCA 034 Gerar Demonstrativo de Contribuições Recebidas

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#200]
Não estamos conseguindo simular um dos pré-requisitos para execução deste caso de uso. Há pendências para conclusão do caso de uso: CDU_SPCA_024_Manter_Origem_de_Recurso ? O sistema não está finalizando o cadastro da Origem de Recursos.
Obs: A execução deste caso de uso: CDU_SPCA_024_Manter_Origem_de_Recurso - impacta na finalização dos casos de uso: 32-33-34-35

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Favor revisar, pois para alguns campos como o destacado na imagem, o sistema não está finalizando a operação.

![sobra de campanha](https://cloud.githubusercontent.com/assets/6584772/8363992/35918a80-1b59-11e5-83a1-9dc43cd57f7d.png)

**Comment by rsantanam** [comment]
Corrigido.

**Comment by jmatil** [comment]
Favor verificar novamente

**Comment by rsantanam** [comment]
Jaílson,

Essa issue esta muito genérica, se possível crie para situações mais específicas caso volte a ocorrer algum problema com Origem de Recurso.

**Comment by jmatil** [comment]
Correção confirmada
