### ISSUE TITLE
HU_SPCA_Excluir Contas Bancarias - Exclusão de Conta Vinculada à Lançamento

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#201]
Há restrição de exclusão de conta vinculada a Lançamento? O sistema não está permitindo a realização de exclusão de registros vinculados e também não emite mensagem de alerta.

![5](https://cloud.githubusercontent.com/assets/6584772/8354732/979b0690-1b20-11e5-99ff-55d6b2ab6af6.PNG)

**Comment by rsantanam** [comment]
Jaílson, o problema acontece porque a conta esta vinculada a uma origem e/ou um pagamento. A documentação não menciona qual o procedimento a ser adotado.

**Comment by jmatil** [comment]
Issue comprendida. Estaremos aguardando uma decisão para ver se atuaremos ou não nesta ação.
