### ISSUE TITLE
HU_SPCA_Incluir Agente Responsavel - Mensagem 32

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#202]
A mensagem destacada abaixo não está sendo emitida conforme exigência da documentação
![agenteresponsavel](https://cloud.githubusercontent.com/assets/6584772/8378338/0dbc5cf6-1bef-11e5-8753-b39a213bb5e2.png)

**Comment by rsantanam** [comment]
Jaílson, o problema acontece porque a conta esta vinculada a uma origem e/ou um pagamento. A documentação não menciona qual o procedimento a ser adotado.

**Comment by rsantanam** [comment]
Jaílson, 

A mensagem é exibida para o cargo/função de Presidente ou Tesoureiro, conforme imagem abaixo:

![image](https://cloud.githubusercontent.com/assets/6524452/8384536/02bc17b4-1c18-11e5-91ce-d0422dcda37a.png)

**Comment by jmatil** [comment]
Compreendido
