### ISSUE TITLE
CDU SPCA 027 Incluir Registro do Pagamento

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SPCA#203]
Prezado,

Dúvida.
Conforme tela em anexo, para o FB1. Incluir Registro do Pagamento no FB.3 a tela "Pesquisar Fornecedor" não tem a opção fechar tela ou voltar.

![1](https://cloud.githubusercontent.com/assets/9218077/8408178/33c708f4-1e44-11e5-8381-a3444996c093.png)

**Comment by rsantanam** [comment]
Kleiber,

O popup é fechado automaticamente ao selecionar um fornecedor ou se clicar no ( X ) da janela do popup. A imagem não esta aparecendo por algum problema no repositório do TSE.

**Comment by kleiberfaria** [comment]
Item verificado !
