### ISSUE TITLE
CDU_SPCA_035_Gerar_Demonstrativo_de_Sobras_de_Campanha - Execução do CDU

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#204]
O caso de uso não simula qualquer ação que possa ser permitido a execução dos fluxos
![35](https://cloud.githubusercontent.com/assets/6584772/8410065/47ecabaa-1e52-11e5-96df-55d3e421ade2.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Confirmado
