### ISSUE TITLE
CDU_SPCA_035_Gerar_Demonstrativo_de_Sobras_de_Campanha - Ação não simulada

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#205]
Não estamos conseguindo simular a exceção 6 Pleito Inválido. Há alguma orientação que poderia nos fornecer para execução da mensagem referente a esta exceção?

![35](https://cloud.githubusercontent.com/assets/6584772/8416158/23a7b51e-1e7a-11e5-8db9-d31606b30484.png)

**Comment by rsantanam** [comment]
Jaílson, essa fluxo não conseguirá ser executado, visto que o campo só permite números.

**Comment by rsantanam** [comment]
Jaílson,

Não vai conseguir simular o fluxo visto que o campo só permite números e a documentação não especifica o que seria um ano inválido.

**Comment by jmatil** [comment]
Compreendido
