### ISSUE TITLE
Qualificaçao do Prestador de Contas - Chave de Ativação

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#206]
O sistema não está gerando a chave de ativação conforme imagem abaixo:

![spca](https://cloud.githubusercontent.com/assets/6584772/8453883/21c54fd0-1fcf-11e5-82b9-3fe8795ef6df.png)

**Comment by rsantanam** [comment]
Jaílson,

Não consegui simular a situação, caso ocorra novamente por favor sinalize.

**Comment by jmatil** [comment]
Item resolvido
