### ISSUE TITLE
CDU SPCA 024 Manter Origem de Recurso - VALIDAÇÃO DE CPF

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#207]
CPF INVÁLIDO está sendo aceito pela aplicação
![cpf](https://cloud.githubusercontent.com/assets/6584772/8463094/808562c8-200e-11e5-8c7e-3c13a9eab830.png)

**Comment by rsantanam** [comment]
Resolvido

**Comment by jmatil** [comment]
Confirmado
