### ISSUE TITLE
CDU SPCA 024 Manter Origem de Recurso - VALIDAÇÃO DE CPF COM MENOS DE 11 POSIÇÕES

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#208]
O sistema não está validando a exceção 9
![cpf](https://cloud.githubusercontent.com/assets/6584772/8463293/85ecbcb0-200f-11e5-921d-b1d42b14f7b4.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Confirmado
