### ISSUE TITLE
CDU SPCA 024 Manter Origem de Recurso - VALIDAÇÃO DE CNPJ

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#209]
O sistema não está validando CNPJ

![cpf](https://cloud.githubusercontent.com/assets/6584772/8463540/82f4e008-2011-11e5-97eb-0fa138dd5502.png)

**Comment by rsantanam** [comment]
Resolvido

**Comment by jmatil** [comment]
Confirmado
