### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Sistema está validando o campo CPF/CNPJ quando a classificação da receita for igual a RONI

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#21]
O sistema está validando o campo CPF/CNPJ quando o usuário informa menos de 11 (CPF) ou 14 (CNPJ) posições. 
Porém a regra de negócio RN70 define "...Quando a classificação da receita for igual a RONI, o sistema não deverá validar o número do CPF ou o número do CNPJ informados, ou seja, o sistema deverá aceitar o número do CPF ou do CNPJ correto ou incorreto."

![erro_validao cpf quando classificaao for igual a roni](https://cloud.githubusercontent.com/assets/6304414/2553216/bb6e5696-b6a2-11e3-9e99-52c687c31406.png)
![erro_validao cnpj quando classificaao for igual a roni](https://cloud.githubusercontent.com/assets/6304414/2553217/bf0530d6-b6a2-11e3-8c41-954cff6bbd51.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão: 2.0.6

**Comment by marasb** [comment]
Defeito corrigido. 
Versão 2.0.12
