### ISSUE TITLE
CDU SPCA 024 Manter Origem de Recurso - VALIDAÇÃO DE CNPJ COM MENOS DE 14 POSIÇÕES

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#210]
O sistema não está validando a exceção abaixo

![cpf](https://cloud.githubusercontent.com/assets/6584772/8463617/3a18029c-2012-11e5-8fdc-1613f53caa37.png)

**Comment by rsantanam** [comment]
Resolvido

**Comment by jmatil** [comment]
Confirmado
