### ISSUE TITLE
CDU SPCA 025 Manter Requisito do Gasto - FE6. CNPJ com menos de 14 posições

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SPCA#214]
Prezados,

O campo [ CPF/CNPJ \* ] não esta validando a MSG024 - O CNPJ deve ser preenchido com 14 (quatorze) posições, se necessário preencher com zeros à esquerda. 

![1](https://cloud.githubusercontent.com/assets/9218077/8478791/dcf3c9c8-20a9-11e5-8d42-17e07e768a58.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
