### ISSUE TITLE
CDU_SPCA_035_Gerar_Demonstrativo_de_Sobras_de_Campanha - Resultado

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#216]
O sistema não está apresentando resultados para gerar o demonstrativo sendo que há origem de recursos cadastrada conforme exigência da RN110.

![35](https://cloud.githubusercontent.com/assets/6584772/8498923/23d15e28-2163-11e5-9009-0cb623e447a2.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
