### ISSUE TITLE
HU SPCA Incluir Endereco do Prestador - Municipio

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#218]
Não foi possível simular a exceção destacada na imagem anexa. 
Emissão da mensagem 036.
![minicipio](https://cloud.githubusercontent.com/assets/6584772/8552277/7ba28ed6-24b2-11e5-9315-8a8ca74cffdc.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
