### ISSUE TITLE
HU SPCA Incluir Endereco do Prestador - CEP

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#219]
Não foi possível simular uma ação com um CEP válido fornecido pela página dos correios conforme solicitação da aplicação.
Há registros cadastrados que possam ser disponibilizados para simularmos esta ação?

![jambis](https://cloud.githubusercontent.com/assets/6584772/8552913/555e2c40-24b6-11e5-9370-0f80fa486539.png)

**Comment by rsantanam** [comment]
As faixas de CEP para DF  são: 
70002900 a 72773010;
e
73005080 a 73403539
Foi identificado um problema na validação que já foi corrigido e esta disponível  para teste.

**Comment by jmatil** [comment]
Correção confirmada
