### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Erro no campo espécie de recurso

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#22]
Quando selecionada a opção Fonte de Recurso igual a "Fundo Partidário" ou "Outros Recursos" o sistema está apresentando a opção "Cartão de Crédito" no campo "Espécie de Recurso ".
Porém a regra "RAP10.  Apresentação da caixa de seleção espécie de recurso", define: "Cartão de crédito – esta opção estará disponível apenas quando for selecionada a informação Fonte do Recurso igual a “Recursos de Campanha”

![erro_validao especie de recurso](https://cloud.githubusercontent.com/assets/6304414/2554321/be1900f0-b6af-11e3-87f4-320ffa33a3be.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.7

**Comment by marasb** [comment]
O erro ainda persiste. Versão 2.0.12
Quando selecionada a opção Fonte de Recurso igual a "Fundo Partidário" ou "Outros Recursos" o sistema está apresentando a opção "Cartão de Crédito" no campo "Espécie de Recurso ".
![erro_espcie de recurso carto de crdito_fundo partidrio](https://cloud.githubusercontent.com/assets/6304414/2582730/dc62d254-b9c8-11e3-9104-53bd70f863b7.png)
![erro_espcie de recurso carto de crdito_outros recursos](https://cloud.githubusercontent.com/assets/6304414/2582735/e1232172-b9c8-11e3-82b7-f64a3eb76ecc.png)

**Comment by rsantanam** [comment]
Resolvido 
Versão 2.0.13

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.14.
