### ISSUE TITLE
CDU SPCA 026 Manter Requisito do Pagamento - FE2. Data Inválida

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SPCA#220]
Prezados,

Para esse fluxo de exceção, não esta sendo possível realizar a apresentação da mensagem MSG031

![1](https://cloud.githubusercontent.com/assets/9218077/8553739/e385fd36-24bb-11e5-8cf0-b9c1c9770a4c.png)

**Comment by rsantanam** [comment]
Kleiber,
Qual foi a data inválida que tentou inserir?

**Comment by rsantanam** [comment]
Kleiber,

A pesquisa com esse tipo de filtragem possui algumas particularidades como pode-se observar nas diversas issues(#93, #97, #119)  abertas a respeito desse campo. Fiz uma correção que atende ao FE2.

**Comment by kleiberfaria** [comment]
Item verificado !
