### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Erro no campo espécie de recurso -  Cartão de Débito

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#23]
Quando selecionada a opção Fonte de Recurso igual a "Fundo Partidário" ou "Outros Recursos" o sistema está apresentando a opção "Cartão de Débito" no campo "Espécie de Recurso ".
Porém a regra RAP10 define: "Cartão de débito: esta opção estará disponível apenas quando for selecionada a informação Fonte do Recurso igual a “Recursos de Campanha”;”.

![erro_validao especie de recurso_carto de dbito](https://cloud.githubusercontent.com/assets/6304414/2554412/e333f286-b6b0-11e3-8b2e-d9777947c44a.png)

**Comment by rsantanam** [comment]
Resolvido pelo BUG 22.
Versão 2.0.7

**Comment by marasb** [comment]
O erro ainda persiste. Versão 2.0.12
Quando selecionada a opção Fonte de Recurso igual a "Fundo Partidário" ou "Outros Recursos" o sistema está apresentando a opção "Cartão de Débito" no campo "Espécie de Recurso ".

![erro_espcie de recurso carto de dbito_fundo partidrio](https://cloud.githubusercontent.com/assets/6304414/2582781/5b1a03a6-b9c9-11e3-84a2-9125e23be365.png)
![erro_espcie de recurso carto de dbito_outros recursos](https://cloud.githubusercontent.com/assets/6304414/2582784/61b519bc-b9c9-11e3-8d5b-e6ffb67c83ea.png)

**Comment by rsantanam** [comment]
Resolvido 
Versão 2.0.13

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.14
