### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Erro validação do campo Número do Documento.

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#24]
Quando selecionada a opção Espécie de Recurso igual a "Transferência Eletrônica", não informado nenhum dado no campo  Número do Documento e acionado o botão "Gravar" o sistema não está apresentando a mensagem de obrigatoriedade do campo Número do Documento.
Porém a regra RN70 define: " Número Documento: Este campo deve ser obrigatoriamente preenchido quando a espécie do recurso for igual a “Depósito em cheque”, “Transferência eletrônica”, “Depósito em espécie”, “Cartão de crédito” e “Cartão de débito”.”;”
![erro_validao do campo nmero do documento - preenchimento obrigatrio](https://cloud.githubusercontent.com/assets/6304414/2555235/1395aedc-b6bc-11e3-9eac-bb9ff208f84f.png)

**Comment by rsantanam** [comment]
Resolvido.
Obs: Versão 2.0.8

**Comment by marasb** [comment]
Defeito corrigido.
Versão 2.0.12
