### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Erro quando a sessão expira

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#25]
Quando o usuário fica algum tempo sem acessar a aplicação, o sistema trava e não permite que usuário faça nenhuma ação do sistema. Sendo assim o usuário deve fechar a página da aplicação e abrir novamente.
Após acessar novamente aplicação e logar no sistema, quando o  usuário acessa a página Origem de Recurso e aciona o botão "Adicionar", o sistema apresenta a tela de erro em anexo.
Para o usuário conseguir acessar novamente a funcionalidade, ele deve sair da aplicação e logar novamente.
Acredito que o sistema deveria se comportar diferente, por exemplo: quando a sessão expirar, o sistema poderia simplesmente sair da aplicação e voltar para a tela de login e não ficar travado. E também não deveria apresentar o erro quando o usuário acessar a funcionalidade.

![erro_xml](https://cloud.githubusercontent.com/assets/6304414/2555379/2c7b3e6a-b6be-11e3-88d9-546882cad740.png)

**Comment by jadossantos** [comment]
Corrigido na versão 2.0.10

**Comment by marasb** [comment]
Defeito corrigido. Versão 2.0.12
