### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Erro na validação do campo Número Autorização - Preenchimento nao obrigatório

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#26]
Quando selecionada a opção Espécie de Recurso igual a "Cartão de Crédito" ou "Cartão de Débito, não informado nenhum dado no campo Número Autorização e acionado o botão "Gravar" o sistema está apresentando a mensagem de obrigatoriedade do campo Número Autorização, porém o caso de uso define este campo como não obrigatório.
A regra RN70 define : "Número Autorização: Este campo deve ser preenchido quando a espécie do recurso for igual a “Cartão de crédito” e “Cartão de débito”.
Nos demais tipos de espécie de recurso, este campo não deve ser apresentado.".
A regra não especifica que este campo é obrigatório e o caso de uso define não obrigatório.
![erro_validao do campo nmero autorizao - preenchimento no obrigatrio](https://cloud.githubusercontent.com/assets/6304414/2555518/8e9afbba-b6c0-11e3-8406-dd89af9171d8.png)

**Comment by rsantanam** [comment]
Resolvido indiretamente pelo bug 24
Versão 2.0.8

**Comment by marasb** [comment]
O defeito persiste na versão 2.0.12. Pois o campo Numero Autorização ainda está sendo validado como obrigatório.
Solicito também a retirada do asterisco de obrigatoriedade do campo.

**Comment by rsantanam** [comment]
Resolvido
Versão 2.0.17

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.17
