### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Erro na validação da obrigatoriedade do campo Quantidade

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#28]
O sistema não está validando a obrigatoriedade do campo "Quantidade" quando informado o campo Espécie do Recurso = Outros títulos de créditos e acionado o botão "Gravar".
Indo contra a regra de negócio RN70 que define : Quantidade: Este campo deve ser obrigatoriamente preenchido quando a espécie do recurso for igual a “Outros títulos de crédito”.

![erro_validao obrigatoriedade campo quantidade](https://cloud.githubusercontent.com/assets/6304414/2566846/57fe18c2-b8cc-11e3-9028-9c3c10c755aa.png)

**Comment by rsantanam** [comment]
Resolvido indiretamente pelo bug 24
Versão 2.0.8

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.12.
