### ISSUE TITLE
HU_SPCA_Identificar o adm do prestador de contas  - O CA8 foi alterado na história

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#3]
O critério de aceitação CA8 foi alterado na história para contemplar a seguinte situação:
• Caso seja informado um período de gestão fora do período de vigência do prestador de contas, o sistema deve apresentar a mensagem MSG063.

**Comment by AllanCruzRosa** [comment]
liberado para teste na versão 2.0.2

**Comment by wesleyreis** [comment]
Defeito corrigido.

Versão da aplicação: 2.0.2

Obs: Testado no ambiente  de integração ( http://integracao.happs.tse.jus.br:9080/spca-ic/).
