### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Erro na validação da obrigatoriedade do campo Fonte de Avaliação

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#30]
O sistema não está validando a obrigatoriedade do campo "Fonte de Avaliação" quando informado o campo Espécie do Recurso = Outros títulos de créditos e acionado o botão "Gravar".
Indo contra a regra de negócio RN70 que define : "Fonte de Avaliação: Este campo deve ser obrigatoriamente preenchido quando a espécie do recurso for igual a “Outros títulos de crédito”."
![erro_validao obrigatoriedade campo fonte de avaliao](https://cloud.githubusercontent.com/assets/6304414/2566882/e908cdbc-b8cc-11e3-9277-0c875735b825.png)

**Comment by rsantanam** [comment]
Resolvido na versão 2.0.9

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.12.
