### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Validação do CPF na inclusão das Origens de Recursos

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#32]
Verificar o comportamento do sistema ao realizar o cadastramento, pois o fluxo de exceção 8 [FE8 - CPF Inválido] não está sendo possível reproduzir, pois o sistema não está validando os dados informados ao campo. Segue imagens destacando o campo e os cadastros aceitos pelo sistema com informações inválidas.
![campo](https://cloud.githubusercontent.com/assets/6584772/2567708/c74bdffa-b8d8-11e3-98c1-7d7270d3fc2a.png)
![cpfs](https://cloud.githubusercontent.com/assets/6584772/2567709/ce30cb6e-b8d8-11e3-86eb-3256ace7b077.png)

**Comment by jadossantos** [comment]
Resolvido na versão 2.0.9

**Comment by jmatil** [comment]
Favor reavaliar o item, pois a não validação ainda persiste conforme destacado na imagem anexa
![campocpf](https://cloud.githubusercontent.com/assets/6584772/2594146/fb7ffda8-ba89-11e3-9fee-7646d88c48ec.png)

**Comment by jadossantos** [comment]
Resolvido novamente na versão 2.0.15

**Comment by jmatil** [comment]
Foi verificado a correção e validação do campo acima citado. Segue imagem para as devidas comparações.

![corrigido](https://cloud.githubusercontent.com/assets/6584772/2602931/88c228d8-bb27-11e3-86e2-62d531cc154d.png)
