### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Ação contrária ao especificado na documentação

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#33]
Verificar o comportamento do sistema, pois ao acessar o menu pela primeira vez o sistema não carrega todos os itens cadastrados, mas após acessar a opção "Pesquisar" sem informar os parâmetros necessários o sistema executa a ação contrária ao especificado na documentação carregando na tela os itens que deveriam ser apresentados no primeiro acesso ao menu. Segue imagem da ação juntamente com um trecho da documentação. Esta ação foi possível ao tentar executar o fluxo de exceção 15 - Parâmetros de pesquisa não informados.
![passo1](https://cloud.githubusercontent.com/assets/6584772/2570938/abc19eb0-b8ff-11e3-816b-7bcb79629333.png)
![resultado](https://cloud.githubusercontent.com/assets/6584772/2570944/bad421b6-b8ff-11e3-9dad-d62c2e661d60.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.11

**Comment by jmatil** [comment]
Item corrigido e apresentando mensagem conforme relatado na documentação.
![corrigido](https://cloud.githubusercontent.com/assets/6584772/2594206/eeda6704-ba8a-11e3-9927-f048fdf0db45.png)
