### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Mensagem não emitida conforme especificado na documentação

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#34]
Verificar a ação do sistema, pois ao simular o fluxo de exceção 5 (Data inicial do período maior que data final do período), o sistema relatou que não existia registro para os parâmetros informados, mas não emitiu a mensagem conforme especificado na documentação. Segue imagem e trecho da documentação anexa para as devidas comparações.
![data](https://cloud.githubusercontent.com/assets/6584772/2571453/5303ffd2-b906-11e3-94ec-e155f1bc2dc1.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.11

**Comment by jmatil** [comment]
Item corrigido e apresentando ação conforme relatado na documentação
![corrigido](https://cloud.githubusercontent.com/assets/6584772/2594269/b84ed2aa-ba8b-11e3-82d8-c0339f626b93.png)
