### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Mensagem contrária ao especificado no fluxo

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#35]
Ao simular uma data da qual não houvesse itens cadastrados o sistema emitiu a mensagem contrária ao especificado na documentação.
![registro](https://cloud.githubusercontent.com/assets/6584772/2571543/4df361d0-b907-11e3-956d-339a4e677827.png)

**Comment by rsantanam** [comment]
O comportamento do sistema é apresentar a mensagem na grid de pesquisa "Nenhum registro encontrado" quando não existe consultado.

**Comment by marasb** [comment]
O defeito deve ter sido corrigido em alguma versão anterior, pois não foi possível reproduzir novamente o erro.
