### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Mensagem emitida mesmo com o Campo CPF/CNPJ preenchido

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#38]
Verificar a ação executada pelo sistema, pois na tentativa de ALTERAR um cadastro com o campo: ORIGEM DO RECURSO  de "Pessoa Física" para "Pessoa Jurídica" preenchendo os campos e acessando a opção gravar, o sistema emitiu a mensagem indicando a inexistência do preenchimento do campo conforme destacado na imagem anexa.

![alterando](https://cloud.githubusercontent.com/assets/6584772/2579992/3c936416-b9a8-11e3-9968-33f48d882bd9.png)

**Comment by rsantanam** [comment]
Resolvido 
Versão 2.0.14

**Comment by jmatil** [comment]
Foi verificada a correção da ação citada acima.
![corrigido](https://cloud.githubusercontent.com/assets/6584772/2595459/d60d95b0-ba9a-11e3-9b5c-8688d0ffa9d9.png)
