### ISSUE TITLE
HU_SPCA_Identificar o adm do prestador de contas - O sistema não está permitindo cadastrar um Prestador de Contas

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#39]
Na tela "Qualificação do Prestador de Contas e Identificação do Administrador" ao tentar cadastrar um prestador de contas, o sistema não realiza a gravação e não retorna nenhuma mensagem de sucesso.
![erro_incluso do prestador de contas](https://cloud.githubusercontent.com/assets/6304414/2580344/89c81b10-b9ac-11e3-8031-acbafb0ac7f1.jpg)

**Comment by jadossantos** [comment]
O erro acima é por causa da CONSTRAINT "UK_USUARIO_NR_TITULO" UNIQUE ("NR_TITULO_ELEITOR"). Pois o usuário tentou cadastrar um Título de eleitor que já existe no banco.

**Comment by jadossantos** [comment]
Acabei de conversar com a Stella sobre este erro e não existe um fluxo de exceção para esta situação. 
Ela irá conversar com Paulo para definir a estratégia para alterarmos o Cado de Uso. Enquanto isso o sistema não tratará o erro acima.

**Comment by marasb** [comment]
Melhoria a ser tratada em iterações futuras.
