### ISSUE TITLE
O sistema não está permitindo colar um conteúdo no campo título de eleitor

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#4]
O sistema não está permitindo colar um conteúdo no campo Título de eleitor utilizando o comando CTRL + C. Isso ocorre em todas as telas que tem título de eleitor.

**Comment by AllanCruzRosa** [comment]
liberado para teste na versão 2.0.2

**Comment by marasb** [comment]
O erro persiste na versão 2.0.2

**Comment by flavioribeirom** [comment]
Liberado para teste

**Comment by marasb** [comment]
O erro ainda está acontecendo no campo Título de Eleitor da funcionalidade Efetuar Login.

**Comment by marasb** [comment]
Defeito corrigido.
