### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Erro na apresentação da classificação das receitas contribução de filiado

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#41]
Ao selecionar a opção Fonte de Recurso = Outros recursos e Origem do Recursos = Pessoa Jurídica, o sistema está apresentando a opção "Contribuição de Filiados" na classificação das receitas.
A opção contribuição de filiados não deve ser apresentada quando a origem de recursos for Pessoa Jurídica.
Verificar regra de negócio RN71.
![erro_classificao da receita contribuio de filiado](https://cloud.githubusercontent.com/assets/6304414/2582421/e7264896-b9c4-11e3-8312-77f7948540ec.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.14

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.14
