### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Erro na apresentação da classificação das receitas Sobras de Campanha

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#42]
Ao selecionar a opção Fonte de Recurso = Recursos para campanha e Origem do Recursos = Pessoa Física, o sistema está apresentando a opção "Sobra de campanha" na classificação das receitas.
A opção sobra de campanha não deve ser apresentada quando a origem de recursos for Pessoa Física.
Verificar regra de negócio RN71.

![erro_classificao da receita sobra de campanha](https://cloud.githubusercontent.com/assets/6304414/2582471/733eda50-b9c5-11e3-9cd9-0e2019ee302c.png)

**Comment by rsantanam** [comment]
Resolvido
Versão 2.0.14

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.14
