### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Erro na apresentação da classificação das receitas Transferência Interpartidária e Intrapartidária

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#43]
Ao selecionar a opção Fonte de Recurso = Outros Recursos ou Recursos para campanha e Origem do Recursos = Pessoa Física, o sistema está apresentando as opções "Transferência Interpartidária" e "Transferência Intrapartidária" na classificação das receitas.
As opções "Transferência Interpartidária" e "Transferência Intrapartidária" não devem ser apresentadas quando a origem de recursos for Pessoa Física.
Verificar regra de negócio RN71.

![erro_classificao da receita transferncia intrapartidria e interpartidria](https://cloud.githubusercontent.com/assets/6304414/2582534/3725c91a-b9c6-11e3-91c5-9b0586b1501a.png)
![erro_classificao da receita transferncia intrapartidria e interpartidria 1](https://cloud.githubusercontent.com/assets/6304414/2582537/41ac8e5a-b9c6-11e3-9398-ae2858148772.png)

**Comment by rsantanam** [comment]
Resolvido
Versão 2.0.14

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.14
