### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Erro na apresentação da espécie de recurso Cartão de Crédito e Cartão de Débito

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#44]
Quando selecionada a opção Fonte de Recurso igual a "Recursos de Campanha" o sistema NÃO está apresentando as opções "Cartão de Crédito" e "Cartão de Débito" no campo "Espécie de Recurso ".
Porém a regra RAP10 define: 
Cartão de crédito – esta opção estará disponível apenas quando for selecionada a informação Fonte do Recurso igual a “Recursos de Campanha”.
Cartão de débito -  esta opção estará disponível apenas quando for selecionada a informação Fonte do Recurso igual a “Recursos de Campanha”.

![erro_espcie de recurso carto de dbito e carto de crdito no aparece qdo selecionado recursos para campanha](https://cloud.githubusercontent.com/assets/6304414/2582822/c186a8b0-b9c9-11e3-9a2a-a3fe83bf600f.png)

**Comment by rsantanam** [comment]
Resolvido
Versão2.0.14

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.14
