### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso_Erro quando o usuário informa um número de CPNJ

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#45]
Quando o usuário informa Origem do Recurso = Pessoa Jurídica e informa um número de CNPJ, ao acionar o botão gravar o sistema não realiza nenhuma ação.

Caminho: Login > Selecionar Prestador de Contas > Home > Cadastro > Origem de Recurso > Incluir

![erro_quando o usurio informa um nmero de cnpj o sistema no realiza nenhuma ao](https://cloud.githubusercontent.com/assets/6304414/2590565/e10a4d1e-ba5e-11e3-91b1-c1fd27eab64a.jpg)

**Comment by rsantanam** [comment]
Mara, não consegui simular a situação, poderia testar novamente?

**Comment by marasb** [comment]
Rogério, o erro permanece.
Seguem os passos:
1) Só informar os campos Origem do Recurso = Pessoa Jurídica e CPF/CNPJ = Número do CNPJ.
2) Acionar o botão Gravar.

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.14
