### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso_Erro na validação de obrigatoriedade quando o usuário informa origem do recurso igual a RONI

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#46]
Quando o usuário informa origem do recurso igual a RONI e aciona o botão "Gravar" o sistema apresenta mensagem de preenchimento obrigatório dos campos  referentes aos Dados de Recebimento.
Porém a regra de negócio RN70 define: 
"Quando o campo Origem do Recurso for igual a “RONI”, somente as informações Data da Entrada/Depósito (Conta Bancária) e Valor R$ são de preenchimento obrigatório. Os demais campos não deverão ser exibidos."
![erro_quando o usurio informa a origem de recurso roni - validao da obrigatoriedade](https://cloud.githubusercontent.com/assets/6304414/2590637/0a478948-ba60-11e3-888c-37532987eacd.jpg)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.14

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.14.
