### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso_Erro na validação de obrigatoriedade dos campos Tipo e Número de Documento.

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#48]
O sistema não está realizando validação da obrigatoriedade dos campos "Tipo" e "Número de Documento" quando o usuário seleciona o campo Espécie do Recurso = Transferência Eletrônica, porém não informa a origem de recurso.

Indo contra a regra de negócio RN70: 
o   Tipo: este campo deve ser apresentado somente quando o campo Espécie do Recurso for igual a “Transferência eletrônica”. Este campo é de preenchimento obrigatório.
o   Número Documento: Este campo deve ser obrigatoriamente preenchido quando a espécie do recurso for igual a “Depósito em cheque”, “Transferência eletrônica”, “Depósito em espécie”, “Cartão de crédito” e “Cartão de débito”.

![erro_erro na validao de obrigatoridade dos campos tipo e numero do documento](https://cloud.githubusercontent.com/assets/6304414/2591351/7f1640de-ba6a-11e3-80ad-3f7f1ef5f01d.jpg)

**Comment by jadossantos** [comment]
Na versão 2.0.15 a validação de obrigatoriedade dos campos "Tipo" e "Número Documento" aconteceu. O problema foi corrigido em uma versão anterior.

![spca issues 48](https://cloud.githubusercontent.com/assets/7116054/2595366/dba0ca5c-ba99-11e3-994e-d92b971ff809.png)

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.16.
