### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso_Erro na validação de obrigatoriedade dos campos Dados do Recebimento

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#49]
O sistema não está realizando validação da obrigatoriedade de nenhum campo referente aos "Dados do Recebimento" quando o usuário seleciona o campo Espécie do Recurso (Qualquer opção), porém não informa a origem de recurso.
![erro_erro na validao de obrigatoridade dos campos dados de recebimento](https://cloud.githubusercontent.com/assets/6304414/2591457/a889a77a-ba6b-11e3-8f4d-70ad7c6de86e.jpg)

**Comment by rsantanam** [comment]
Resolvido
Versão 2.0.16

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.16
