### ISSUE TITLE
HU_SPCA_Efetuar login no sistema - Falha HU015_CA05

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#5]
FALHA HU015_CA05

1º Passo: O administrador registrou um usuário com perfil de consulta. Dados abaixo:
CPF: 861.545.745-09
TE: 754229347536
NOME: KAKA
2º Passo: O usuário KAKA não efetou o registro de novo usuário (botão ACESSAR O SPCA NOVO USUARIO)
3º Passo: O Usuário KAKA, sem o registro de novo usuário, tentou acesso ao sistema preenchendo os campos da parte Login – acesso a usuários cadastrados no SPCA, preenchendo os campos CPF, Título de Eleitor e Senha. Ao clicar em login apareceu a seguinte mensagem: “Senha inválida.”
- Considerações: não deveria aparecer essa mensagem, deveria informar que o usuário não estava cadastrado no sistema. Esse procedimento está em desacordo com o CA5 da HU015

"CA5    O sistema deverá validar as informações através do cadastro de usuário:
• Caso o usuário não seja localizado, o sistema apresentará mensagem MSG045;"

"MSG045 Usuário não cadastrado"

**Comment by AllanCruzRosa** [comment]
liberado para teste na versão 2.0.2

**Comment by marasb** [comment]
Defeito corrigido
