### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso_Inserir asterisco de obrigatoriedade no campo Número do Documento.

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#50]
Quando o usuário acessa a tela Origem de recurso, foi observado que o campo Número Documento não  apresenta o asterisco de obrigatoriedade, porém quando acionado o botão "Gravar", o sistema apresenta a mensagem de campo de preenchimento obrigatório.
Sugiro que nessa tela inicial o sistema apresente o asterisco de obrigatoriedade no campo Número do Documento, visto que ele está sendo validado.

Porém o comportamento desse campo nas situações abaixo está correto e deve ser mantido :
- Quando selecionada a espécie de recurso = Ordem Bancária, o sistema apresenta o campo Número do Documento sem o asterisco.
- Quando selecionada a espécie de recurso = Outros títulos de crédito o sistema não apresenta o campo Número do Documento.
- Quando selecionada as demais espécie de recurso o sistema apresenta o campo Número do Documento com o asterisco de obrigatoriedade.
  ![erro_inserir asterisco de obrigatoriedade no campo nmero do documento](https://cloud.githubusercontent.com/assets/6304414/2592236/6e95cb54-ba73-11e3-8e62-43362d0926f3.jpg)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.16

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.16.
