### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso_Erro tamanho do campo Nome/Razão Social

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#51]
O campo Nome/Razão Social está aceitando apenas 70 caracteres, sendo que o caso de uso define o tamanho do campo 300 caracteres.

**Comment by rsantanam** [comment]
Resolvido versão 2.0.17

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.17
