### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso_Erro na apresentação do campo Banco (Destino)

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#52]
Atualmente temos as seguintes contas bancárias cadastradas no sistema ( Cadastro > Conta Bancária):
001-Banco do Brasil S.A. - Recursos Para Campanha  
003-Banco da Amazônia S.A. - Outros Recursos  
001-Banco do Brasil S.A. - Fundo Partidário  
012-Banco Standard de Investimentos S.A.     - Fundo Partidário

Porém no cadastro de origem de recurso, ao selecionar a fonte de recurso Fundo Partidário, o sistema apresenta as opções abaixo no banco de Destino:
000 Banco Bankpar S.A.
001 Banco do Brasil S.A.
001 Banco do Brasil S.A.
012 Banco Standard de Investimentos S.A.

O banco 001 Banco do Brasil S.A. está sendo apresentada duas vezes e o banco 000   Banco Bankpar S.A. aparece mesmo sem está cadastrado nas contas bancárias de fundo partidário.
Esse comportamento se repete para as outras fontes de recursos selecionada.

O regra de negócio RN70 define: "...As informações bancárias de destino devem ser obrigatoriamente preenchidas. Os dados deverão ser INFORMADOS conforme o conteúdo da Fonte de Recurso selecionada...".
A regra deixa claro que os dados deverão se informados conforme o conteúdo da fonte de recurso selecionada, ou seja, o usuário deverá informar os dados da conta (Banco, Agencia e Conta) igual ao conteúdo de alguma conta bancária cadastrada para a fonte de recurso seleciona. Mas a regra não fala que o conteúdo deve ser APRESENTADO conforme fonte de recurso selecionada.
Sendo assim a informação Banco deve apresentar o domínio definido no RAP1, ou seja, apresentar todos os bancos independente da fonte de recurso selecionada.

**Comment by rsantanam** [comment]
Mara, não consegui simular a situação. Segue abaixo as imagens :1234: 
1 - Cadastro de Conta Bancária
![contas cadastradas](https://cloud.githubusercontent.com/assets/6524452/2603308/f47ab784-bb2c-11e3-819e-1814c97daf99.png)

2 - Cadastro Origem recurso
![origem_recursos_campanha](https://cloud.githubusercontent.com/assets/6524452/2603339/858d4e62-bb2d-11e3-9f0d-f1a734b4d8bb.png)
!
![origem_fundo_partidario](https://cloud.githubusercontent.com/assets/6524452/2603355/ab1ae22a-bb2d-11e3-9abb-28e9977f62ac.png)
[origem_outros_recursos](https://cloud.githubusercontent.com/assets/6524452/2603340/858ff752-bb2d-11e3-8256-f41167061d8e.png)
![origem_fundo_partidario](https://cloud.githubusercontent.com/assets/6524452/2603341/8590374e-bb2d-11e3-8674-ac7d08688270.png)

**Comment by marasb** [comment]
A regra deixa claro que os dados deverão se informados conforme o conteúdo da fonte de recurso selecionada, ou seja, o usuário deverá informar os dados da conta (Banco, Agencia e Conta) igual ao conteúdo de alguma conta bancária cadastrada para a fonte de recurso seleciona. Mas a regra não fala que o conteúdo do banco deve ser EXIBIDO conforme fonte de recurso selecionada.
Sendo assim a informação Banco deve apresentar o domínio definido no RAP1, ou seja, apresentar todos os bancos independente da fonte de recurso selecionada.

**Comment by raphaelgalvao** [comment]
Bom dia Mara,

Segue nossos pontos de vista abaixo:

1) Da forma que está implementado atualmente, o usuário não é induzido ao erro, uma vez que o mesmo só selecionará Contas Bancarias que estejam vinculadas a Fonte selecionada.

2) Da maneira implementada atualmente, não temos problemas de performance, por exemplo, se existissem mais de 300 contas bancarias cadastradas, o que no meu ponto de vista é totalmente possível de acontecer, todas essas informações listadas em um combo, dificulta a utilização para o próprio usuário final.

3) Entendi o seu ponto de vista explicado acima, porém a regra apresentada deixa brecha, para interpretação dúbia quando cita: "Os dados deverão ser informados conforme o conteúdo da Fonte de Recurso selecionada."

4) Da maneira que está implementada, não damos brecha ou possibilidade de indução do usuário ao erro. Facilitando a utilização do sistema, evitando a validação de regras desnecessárias pois o próprio fluxo do sistema já trata isso.

5) Creio que a alteração da documentação para deixar explicito essa dependência teria muito menos impacto que a alteração da aplicação para funcionar da maneira citada por você.

Com quem poderíamos conversar para que isso fosse alterado no negocio?

**Comment by marasb** [comment]
Prezados,

Conversei com o Jardel sobre as considerações levantadas e ele informou que nas próximas iterações ele irá alterar essa apresentação, para ficar conforme definido na parte de aplicação, ou seja, apresentar uma lista com as contas já cadastradas.
Ele informou que nesse momento a documentação não será mais alterada.
Porém ele concordou em deixar implementado como está, ou seja, apresentar somente os bancos conforme o conteúdo da Fonte Selecionada.

**Comment by marasb** [comment]
Porém deve ser corrigido o erro informado no primeiro comentário.

Atualmente temos as seguintes contas bancárias cadastradas no sistema ( Cadastro > Conta Bancária):
001-Banco do Brasil S.A. - Recursos Para Campanha
003-Banco da Amazônia S.A. - Outros Recursos
001-Banco do Brasil S.A. - Fundo Partidário
012-Banco Standard de Investimentos S.A. - Fundo Partidário

Porém no cadastro de origem de recurso o sistema apresenta o seguinte comportamento:
1) Quando selecionada a fonte de recurso Fundo Partidário o sistema apresenta as opções abaixo no banco de Destino:
000 Banco Bankpar S.A.
001 Banco do Brasil S.A.
001 Banco do Brasil S.A.
012 Banco Standard de Investimentos S.A.
Comportamento esperado: O correto seria apresentar apenas os bancos 001 e 012.

2) Quando selecionada a fonte de recurso "Outros Recursos"o sistema apresenta as opções abaixo no banco de Destino:
001-Banco do Brasil S.A.
003-Banco da Amazônia S.A.
184 Banco Itaú BBA S.A.
Comportamento esperado: O correto seria apresentar apenas o banco 003.

3) Quando selecionada a fonte de recurso "Recursos para campanha"o sistema apresenta as opções abaixo no banco de Destino:
001-Banco do Brasil S.A.
409 UNIBANCO - União de Bancos Brasileiros S.A.
Comportamento esperado: O correto seria apresentar apenas o banco 001.

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.19

**Comment by marasb** [comment]
Defeito corrigido.
