### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso_Erro na validação de obrigatoriedade quando o usuário informa origem do recurso igual a RONI 

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#53]
Quando o usuário informa origem do recurso igual a RONI e aciona o botão "Gravar" o sistema apresenta mensagem de preenchimento obrigatório dos campos referentes aos Dados de Recebimento.
Porém a regra de negócio RN70 define:
"Quando o campo Origem do Recurso for igual a “RONI”, somente as informações Data da Entrada/Depósito (Conta Bancária) e Valor R$ são de preenchimento obrigatório. Os demais campos não deverão ser exibidos."

Esse erro já havia sido registrado e corrigido anteriormente.

**Comment by rsantanam** [comment]
Resolvido
Versão 2.0.18

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.18.
