### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso_Erro na quando o usuário informa 300 caracteres no campo Nome/Razão Social

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#54]
Na tela de cadastro de origem de recurso ao informar um Nome/Razão Social com 300 caracteres, que é o comportado pelo campo, ao acionar o botão "Gravar" o sistema não realiza a gravação.

**Comment by rsantanam** [comment]
Stella a documentação deve ser ajustada para atender ao tamanho máximo do campo Nome/RazãoSocial, conforme as tabelas de PESSOA_JURIDICA e PESSOA_FISICA. Nas tabelas mencionadas temos 70 como o tamanho máximo para uma pessoa física e 300 para uma pessoa jurídica.

**Comment by stellamara** [comment]
O caso de uso foi corrigido.

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.18

**Comment by marasb** [comment]
Defeito corrigido. Versão 2.0.19
