### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Mensagem emitida após alteração

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#55]
Verificar o comportamento do sistema, pois após alterar um cadastro que estava com o campo: Tipo Fornecedor - "Pessoa Física" para "Pessoa Jurídica" e preencher os campos necessários para o cadastramento, o sistema emitiu a mensagem de obrigatoriedade mesmo com o campo já preenchido. Segue imagem com destaque da ação.

![alterar](https://cloud.githubusercontent.com/assets/6584772/2654960/2e99ba72-bfde-11e3-9210-4d39e37c2d0a.png)

**Comment by jadossantos** [comment]
Corrigido.

**Comment by jmatil** [comment]
Foi verificado que o sistema não está mais emitindo a mensagem conforme evidenciado acima. Item corrigido.
