### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso _ Erro na quantidade de registros apresentados no resultado da pesquisa

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#56]
A aplicação está apresentando no resultado de pesquisa de origem de recursos 10 registros por página, porém o RAP 12 define: "O sistema deve apresentar 30 registros por página no resultado da pesquisa."
![erro_rap12](https://cloud.githubusercontent.com/assets/6304414/2659776/0087515a-c018-11e3-8750-c9d66af52289.jpg)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.19

**Comment by marasb** [comment]
defeito corrigido.
