### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso _ Erro na mensagem da exceção FE15

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#57]
Na consulta de origem de recurso, quando o sistema não encontra registro que atenda ao parâmetro informado está apresentando a mensagem "Nenhum registro encontrado".
Porém no caso de uso está definido que deve ser apresentada a mensagem MSG088 "Não existe registro para o parâmetro informado."

![erro_mensagem da exceo fe15](https://cloud.githubusercontent.com/assets/6304414/2660388/63f60e32-c01f-11e3-91f3-97482ab335e7.jpg)

**Comment by rsantanam** [comment]
Resolvido
versão 2.0.19

**Comment by marasb** [comment]
Resolvido na versão 2.0.19
