### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso _ Erro na quantidade de caracteres do campo Filtrar

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#58]
Na tela de pesquisa de origem de recurso, o campo Filtrar está aceitando mais de 50 caracteres.
Porém no caso de uso está definido 50 caracteres.

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.20

**Comment by marasb** [comment]
Defeito corrigido.
Versão 2.0.20.
