### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso _ Erro na apresentação do campo Espécie de Recurso

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#59]
Após incluir uma origem de recurso, o sistema retorna para a tela de consulta.
Porém na tela de consulta o campo "Espécie de Recurso" na grid de pesquisa não aparece preenchido.
O sistema só apresenta esse campo preenchido quando o usuário acessa novamente a página de pesquisa.

![erro - especie de recurso](https://cloud.githubusercontent.com/assets/6304414/2669540/7f38442c-c0c3-11e3-8692-0c9d41cfef12.png)

**Comment by rsantanam** [comment]
Resolvido
versão 2.0.20

**Comment by marasb** [comment]
Defeito corrigido. Versão 2.0.20
