### ISSUE TITLE
HU_SPCA_Alterar senha do usuario do prestador de contas - Erro ao tentar gravar senha de um usuario parcial

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#6]
Na tela Alterar Senha do Usuário, foi informado o CPF e Título de Eleitor de um usuário que possui apenas o cadastro parcial (cadastro realizado no vínculo), ao alterar o foco do cursor o sistema apresenta a mensagem "Usuário não cadastrado", corretamente.
1ª Erro: Ao informar a senha,  a confirmação da senha e acionar o botão Gravar, o sistema apresenta as mensagens:
    O campo Nome é de preenchimento obrigatório.
    O campo Data Nascimento é de preenchimento obrigatório.
    O campo Nome da Mãe é de preenchimento obrigatório.
Nessa situação o sistema não deverá validar a obrigatoriedade desses campos, pois esses campos não são habilitados para edição.

2º Erro: Ao informar a senha que não obedeça a regra de formação, com uma quantidade de caracteres inferiores a dez ou a confirmação da senha divergente da senha informada, o sistema está apresentando as respectivas mensagens de críticas. Sendo que o correto é o sistema apresentar primeiramente a mensagem "Usuário não cadastrado" para depois realizar as demais validações.
![bug_161_persiste](https://f.cloud.github.com/assets/6304414/1930407/8d4caa44-7eab-11e3-8174-87a64c0f39c5.png)
![erro na validao de usuario nao cadastrado](https://f.cloud.github.com/assets/6304414/1930416/bb3542a4-7eab-11e3-9130-33e6c2573911.png)

**Comment by AllanCruzRosa** [comment]
liberado para teste na versão 2.0.2

**Comment by wesleyreis** [comment]
Teste de confirmação realizado.

Ambiente de integração: http://integracao.happs.tse.jus.br:9080/spca-ic/
Versão: 2.0.1
