### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso _ O sistema apresenta o campo Nome/Razao Social carregado

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#60]
Quando o usuário informa um CNPJ/CPF que já está cadastrado na origem de recurso o sistema apresenta o campo Nome/Razão Social carregado. 
Porém o caso de uso ou regra de negócio não informa que esse deve ser o comportamento do campo.

![erro_sistema carrega os dados nome-razo social incorretamente](https://cloud.githubusercontent.com/assets/6304414/2671082/4b4be32c-c0d6-11e3-858c-6e1277e88e5b.png)

**Comment by raphaelgalvao** [comment]
Boa tarde Mara,

Esse item foi alinhado hoje a tarde em uma reunião com a SEBD e SEAD e eles irão alinhar internamente o conceito das tabelas e o que a aplicação deve tratar e como deverá ser feito a posteriori.

A entrega atual será realizada da maneira que se encontra atualmente.
