### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso _ Campo Nome/Razão social não aparece disponível para edição na tela de alteração

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#61]
O campo Nome/Razão social não aparece editável na tela de alteração de origem de recurso.
O caso de uso define este campo como Editável.

![erro_campo nome-razo social no est editvel](https://cloud.githubusercontent.com/assets/6304414/2671143/fcddfe68-c0d6-11e3-9d20-66e911351f25.jpg)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido.
