### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Campo disponível para edição

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#62]
Verificar o comportamento do sistema, pois para o cadastro como pessoa jurídica o sistema está com o campo CPF/CNPJ disponível para edição após acessar a opção "Detalhar origem de recurso". Segue imagem para as devidas comparações.
![detalhar](https://cloud.githubusercontent.com/assets/6584772/2671461/d6abcaaa-c0da-11e3-88d8-191fe7423517.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido.
