### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso _ Sistema apresenta mensagem de exceção do título incorreatamente

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#63]
Ao informar um título de eleitor inválido ou com menos de 14 caracteres e acionado o botão gravar o sistema apresenta mensagem de exceção. Porém quando altero a classificação da receita para outro tipo que não seja "Contribuição de Filiado" e aciono o botão gravar o sistema continua apresentando as mensagens de exceção do título, mesmo sem o título aparecer na tela.

![erro_sistema apresenta mensagem de exceo do ttulo errada](https://cloud.githubusercontent.com/assets/6304414/2679102/2de25be4-c16d-11e3-994f-9368d47db452.jpg)

**Comment by rsantanam** [comment]
Resolvido
Versão 2.0.25

**Comment by marasb** [comment]
Defeito corrigido.
Versão 2.0.26
