### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso _ Mensagem incorreta quando o usuario nao informa CNPF/CPF na alteração

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#64]
Na tela de alteração de origem de recurso, quando o usuário apaga o CPF e CNPJ e aciona o botão Gravar o sistema apresenta a mensagem " O CPF deve ser preenchido com 11(onze) posições, se necessário preencher com zeros à esquerda." ou "O CNPJ deve ser preenchido com 14(quatorze) posições, se necessário preencher com zeros à esquerda.".
Porém o correto é o sistema apresentar mensagem de preenchimento de campo obrigatório, visto que os campos não estão preenchidos.

Passos:
1) Acionar o botão de alteração
2) Apagar o campo CPF/CNPJ
3) Acionar o botão Gravar

![erro_campo cnpj mensagem incorreta](https://cloud.githubusercontent.com/assets/6304414/2679183/be6545ea-c16e-11e3-97ee-f14a1be50933.jpg)
![erro_campo cpf mensagem incorreta](https://cloud.githubusercontent.com/assets/6304414/2679185/c22b74b0-c16e-11e3-9784-ac8309bf9135.jpg)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.25

**Comment by marasb** [comment]
Defeito corrigido versão 2.0.26.
