### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso - Impossibilidade de Finalização do Cadastro

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#66]
Ao tentar finalizar o cadastramento selecionando no campo - Fonte de Recurso: "Recursos para Campanha" e disponibilizar os dados bancários "de Origem" com informações já cadastras no menu "Cadastro / Conta Bancária", o sistema não efetua o cadastro e nem emite uma mensagem que restrinja a ação. Verificar o comportamento do sistema, pois esta restrição não está relatada na documentação disponível.(CDU_SPCA_024_Manter_Origem_de_Recurso.docx).
Obs. "As informações preenchidas foram as mesmas: Banco, Agência e Conta Corrente".
![cadastro](https://cloud.githubusercontent.com/assets/6584772/2680405/465e9538-c182-11e3-8251-0f13b2773778.png)

![contas_bancarias](https://cloud.githubusercontent.com/assets/6584772/2680407/4ee5ad22-c182-11e3-9aa6-4b0e88e13c8e.png)

**Comment by rsantanam** [comment]
Matil, não consigo simular o erro. Poderia detalhar ou retestar?

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.31

**Comment by jmatil** [comment]
Verificada a correção conforme versão especificada acima.
