### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Erro no nome do campo Tipo de Fornecedor

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#67]
Na tela de cadastro de registro do gasto está sendo apresentado o campo "Tipo Fornecedor", sendo que no caso de uso está definido "Tipo de Fornecedor".

![erro_nome do campo tipo de fornecedor](https://cloud.githubusercontent.com/assets/6304414/2680874/4992a28a-c187-11e3-8408-618eb7bfa5d6.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.20
