### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Erro no campo Número do Documento

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#68]
Na tela de registro de gasto, o campo Número do Documento está aceitando apenas caracteres numéricos, sendo que no caso de uso está definido Alfanumérico.

![erro_sistema no aceita caracteres alfunumrico](https://cloud.githubusercontent.com/assets/6304414/2680918/d30d4416-c187-11e3-9fcc-04cd17f5345e.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido na versão 2.0.20.
