### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Erro no campo Código da Natureza do Gasto

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#69]
Na tela de cadastro de gasto, o campo "Código da Natureza do Gasto" possui os erros abaixo:
1) Aceita caracteres alfanuméricos, sendo que no caso de uso está descrito Numérico.
2) Não possui máscara, sendo que no caso de uso está definida a Máscara: 0.0.0.00.00.00.00.
3) Está aceitando 17 caracteres, sendo que no caso de uso define 11 caracteres.

![erro_campo cdigo da natureza do gasto](https://cloud.githubusercontent.com/assets/6304414/2681034/ba5720e4-c188-11e3-8933-98d0d0bbb8c7.png)

**Comment by jadossantos** [comment]
Corrigido.

**Comment by marasb** [comment]
Defeito corrigido.
