### ISSUE TITLE
HU_SPCA_Incluir Endereco do Prestador - Erro ao acessar a funcionalidade com perfil de Consulta

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#7]
Ao acessar a funcionalidade Qualificação (Endereço do Prestador de Contas) com um usuário perfil Consulta, o sistema está apresentando a mensagem de erro: mensagen.restricao.perfil.pesquisa.
Sendo que de acordo com a história: "...Esta opção poderá ser acessada pelos usuários com perfil “Administrador”, “Operador” e “Consulta”.
O usuário com perfil “Consulta” não poderá incluir as informações de qualificação. Neste caso, o sistema deve apresentar a mensagem MSG060."
![erro ao tentar acessar a qualificao do prestador com perfil consulta](https://f.cloud.github.com/assets/6304414/1930585/df4777e4-7eaf-11e3-9a9a-87cffe4941a7.png)

**Comment by AllanCruzRosa** [comment]
liberado para teste na versão 2.0.2

**Comment by marasb** [comment]
Corrigido.
