### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Não está sendo possível atualizar lista de gasto

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#70]
Na tela de cadastro de gasto não está sendo possível "Atualizar Lista" de gastos, pois ao clicar no campo Valor o sistema apaga os campos Código e Descrição da natureza do gasto.
Passos:
1) Acessar a tela de cadastro de gasto (Cadastro > Aplicação de Recursos > Incluir)
2) Informar o campo Codigo da Natureza do Gasto.
3)  Informar o campo Descrição da Natureza do Gasto.
4) Ao clicar no campo Valor o sistema apaga os campos Código e Descrição da Natureza do Gasto.
5) Ao clicar em Atualizar Lista, o sistema apresenta mensagem de obrigatoriedade dos campos.

**Comment by marasb** [comment]
Joel,
Conforme conversado com você e Stella o comportamento deve ser o seguinte:
Caso o usuário informe um código da natureza do gasto inexistente o sistema deve apresentar a mensagem "Código da natureza do gasto inexistente." e limpar o campo.
Caso o usuário informe uma descrição da natureza do gasto inexistente o sistema deve apresentar apresenta a mensagem "Descrição da natureza do gasto inexistente." e limpar o campo.

Stella,

Favor alterar o caso de uso para contemplar a situação acima.

**Comment by jadossantos** [comment]
Implementado na versão 2.0.26.

**Comment by stellamara** [comment]
Documentação atualizada.

**Comment by marasb** [comment]
Defeito corrigido.
