### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Erro no campo descrição

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#71]
Na tela de cadastro de registro de gasto foi observado que o campo Descrição aparece visível independente do "Tipo do Documento" de selecionado.
Porém a regra de negócio define: 
"Descrição: Este campo será obrigatoriamente preenchido e deve ser exibido somente quando o campo Tipo de Documento for igual a “Outros”.

![erro_erro campo descrio](https://cloud.githubusercontent.com/assets/6304414/2682940/ec2ccbb8-c1a2-11e3-93e7-97f18bf1d934.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido
