### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Falta asterisco de obrigatoriedade no campo Número do documento

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#72]
Na tela de cadastro de origem de recurso quando o usuário seleciona o tipo de documento "Documento Fiscal" o campo Número do documento torna-se obrigatório, sendo assim nessa situação este campo deve apresentar o asterisco de obrigatoriedade.

![erro_falta asterisco do campo numero do documento](https://cloud.githubusercontent.com/assets/6304414/2682994/a6d86c56-c1a3-11e3-83a9-44aceba2ab6f.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido.
