### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Erro nos caracteres especiais do campo Descrição da Natureza do Gasto

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#73]
Foi observado que os caracteres especiais do campo Descrição da Natureza do Gasto estão sendo apresentados desconfigurados.
Exemplo: TRANSFERÃ¿NCIAS EFETUADAS

![erro_erro nos caracteres especiais do campo descrio da natureza do gasto](https://cloud.githubusercontent.com/assets/6304414/2683238/709e2a32-c1a7-11e3-9ef7-be7e8cf02499.png)

**Comment by jadossantos** [comment]
Iremos remover todos os registros de NATUREZA_GASTO e GASTO_NATUREZA_GASTO e inserir novamente para corrigir o problema. Fizemos a solicita ao SEAD/SEBD pelo número 23314.

**Comment by jadossantos** [comment]
Feito.

**Comment by marasb** [comment]
Defeito corrigido
