### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - O sistema não está validando a obrigatoriedade dos campos Descrição do Gasto/Documento

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#74]
O sistema não está validando a obrigatoriedade dos campos Descrição do Gasto/Documento (Código da Natureza do Gasto, Descrição da Natureza do Gasto e Valor) quando acionado o botão "Gravar".
Sendo assim o sistema está permitindo inserir um registro de gasto sem que tenha sido registrada uma natureza de gasto.

![erro_obrigatoriedade dos campos descrio do gasto-documento](https://cloud.githubusercontent.com/assets/6304414/2684101/2f40c6d8-c1b3-11e3-8456-da944b0fcfb2.png)

**Comment by jadossantos** [comment]
A obrigatoriedade dos campos supracitados são referentes a ação do botão "Atualizar lista". Não identifiquei essa condição de obrigatoriedade no CDU.

**Comment by marasb** [comment]
O defeito será fechado, pois realmente não foi inserido regra de negócio informando que não poderá ser inserido um gasto sem que a lista de natureza de gasto tenha registro cadastrado.
