### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Descrição do Item

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#75]
Verificar o item destacado no sistema em comparação ao exigido na documentação. Segue imagem para as devidas comparações.
Ação disponível na aba "Pagamento" opção "Incluir"
![valortotal](https://cloud.githubusercontent.com/assets/6584772/2694786/2cbf3d1e-c3c9-11e3-8360-81728e5f9719.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Verificado a correção conforme imagem anexa

![corrigido](https://cloud.githubusercontent.com/assets/6584772/2699536/be7a01ec-c407-11e3-89e6-d44c43a64d90.png)
