### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Mensagem emitida ao informar filtro

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#76]
Verificar o comportamento do sistema, pois foi emitida uma mensagem de erro ao tentar executar a ação.
O sistema não está retornando o resultado para o parâmetro informado, somente para uma pesquisa geral, ou seja, os resultados só são apresentados caso ator não informe parâmetros e acesse diretamente a opção "Pesquisar".

![passo1](https://cloud.githubusercontent.com/assets/6584772/2698266/30595430-c3f8-11e3-95ad-efb33e0dbf8c.png)

![passo2](https://cloud.githubusercontent.com/assets/6584772/2698269/35f951a6-c3f8-11e3-8e23-e6db858a2277.png)

![passo3](https://cloud.githubusercontent.com/assets/6584772/2698271/3ad04f90-c3f8-11e3-8e65-380641e62784.png)

![resultado](https://cloud.githubusercontent.com/assets/6584772/2698272/405042cc-c3f8-11e3-8935-4b78f9db2df2.png)

**Comment by jadossantos** [comment]
Corrigido.

**Comment by jmatil** [comment]
Verificado a correção do item. Segue imagem para as devidas comparações.

![corrigido](https://cloud.githubusercontent.com/assets/6584772/2718883/6614145c-c556-11e3-9923-2f6da14a87de.png)
