### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Divergência de Mensagens

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#77]
Verificar a mensagem emitida pelo sistema, pois está contrária a especificada na documentação.

![datainvalida](https://cloud.githubusercontent.com/assets/6584772/2698693/6bababc8-c3fd-11e3-99c0-42a3557cbaec.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.27

**Comment by jmatil** [comment]
Verificado a correção do item. Segue imagem para as devidas comparações.

![corrigido](https://cloud.githubusercontent.com/assets/6584772/2706342/aca51cfe-c48e-11e3-9c37-ed8056f3d157.png)
