### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Mensagem emitida

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#78]
Verificar a mensagem emitida pelo sistema, pois está contrária à exigida na documentação.

![mensagem](https://cloud.githubusercontent.com/assets/6584772/2698918/651b4374-c400-11e3-9c48-21dfa7246e26.png)

**Comment by jadossantos** [comment]
Corrigido.

**Comment by jmatil** [comment]
Verificado a correção da evidência. Segue imagem para as devidas comparações.

![corrigido](https://cloud.githubusercontent.com/assets/6584772/2706365/566c57b6-c48f-11e3-8695-990ebf17c689.png)
