### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Comportamento divergente

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#79]
Verificar o comportamento do sistema, pois não foi possível simular o fluxo FE3 - "Parâmetro de pesquisa não informado", ou seja, caso usuário não informe o parâmetro e acesse diretamente o botão "PESQUISAR" o sistema deveria emitir a mensagem e não apresentar o resultado.

![pesquisageral](https://cloud.githubusercontent.com/assets/6584772/2706513/aaddab1c-c492-11e3-8812-71677e871982.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.28

**Comment by jmatil** [comment]
Problema persiste para versão indicada.

![acao](https://cloud.githubusercontent.com/assets/6584772/2711492/3ea4af04-c4ce-11e3-9fc9-5a7dc157da7f.png)

**Comment by jmatil** [comment]
Verificado a correção do item. Segue imagem para as devidas comparações.

![corrigido](https://cloud.githubusercontent.com/assets/6584772/2718899/bb4292e6-c556-11e3-8e9a-e8e3fb373107.png)
