### ISSUE TITLE
HU_SPCA_Incluir usuario do prestador de contas no SPCA-Cadastro - Erro na mensagem do windows para gravar senha

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#8]
Ao cadastrar um usuário do sistema, registrou-se as informações do CPF, TE, NOME, e a respectiva senha. No entanto ao se gravar as informações o navegador questionou se desejava memorizar a senha do usuário "Número do CPF”.
O correto é apresentar o nome do usuário e não o número do CPF.
![erro na mensagem do windows para memorizar senha](https://f.cloud.github.com/assets/6304414/1931029/7397d7ec-7eb8-11e3-9664-af324064b0df.png)

**Comment by AllanCruzRosa** [comment]
Mara,
O correto e o numero do CPF mesmo, pois ele é o identificador do usuário.

**Comment by marasb** [comment]
Defeito finalizado conforme orientação do desenvolvedor.
