### ISSUE TITLE
CDU_SPCA_027_Incluir_Registro_do_Pagamento - Mensagem não emitida

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#80]
Verificar a possibilidade de emissão da mensagem de advertência ao informar uma data inválida no item de pesquisa de fornecedor. O sistema apresentou o resultado de todos os itens cadastrados após acesso conforme imagem anexa.

![mensagem](https://cloud.githubusercontent.com/assets/6584772/2706627/a33fa1b0-c494-11e3-9f72-c8382b4b45f8.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.29

**Comment by jmatil** [comment]
Verificado a correção. Segue imagem para as devidas comparações

![corrigido](https://cloud.githubusercontent.com/assets/6584772/2718825/7139d214-c555-11e3-9565-955268ed3c6f.png)
