### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Ajustar os asteriscos de obrigatoriedades

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#81]
Na tela de cadastro de gasto, o asterisco dos campos Data da Emissão/Contratação e Código da Natureza do Gasto  está aparecendo na linha abaixo do label.
O asterisco deve aparecer na mesma linha do label.

![erro_asterisco de obrigatoriedade](https://cloud.githubusercontent.com/assets/6304414/2706733/a64d5288-c496-11e3-84b6-1d19a362d5c2.png)

**Comment by jadossantos** [comment]
Essa característica é por causa do tamanho definido para a tag "label", que tem o tamanho de 12% definido no arquifvo "http://cdn.tse.jus.br/estatico/final/css/spca_padrao.css".

**Comment by marasb** [comment]
De acordo com as notas do desenvolvedor não será possível corrigir o defeito.
