### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Sistema não apresenta mensagem de confirmação na exclusão de natureza de gasto

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#82]
O sistema não está apresentando a mensagem MSG007 quando o usuário solicita a exclusão dos dados da natureza do gasto.
Quando o ator solicita a exclusão dos dados da natureza do gasto o sistema deve apresentar a mensagem MSG007.

**Comment by jadossantos** [comment]
Corrigido.

**Comment by marasb** [comment]
Defeito corrigido.
