### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Mensagem emitida

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#84]
Verificar o comportamento do sistema, pois ao simular o fluxo [FE6 CNPJ com nenos de 14 posições] o sistema emitiu uma mensagem contrária a especificada na documentação.

![mensagem](https://cloud.githubusercontent.com/assets/6584772/2711216/6c80d3e2-c4cb-11e3-9a04-2cdf64dbc4e7.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Verificado a alteração. Segue imagem para as devidas comparações.

![corrigido](https://cloud.githubusercontent.com/assets/6584772/2718864/16d4cf3a-c556-11e3-8f97-9e5d2b5b9de3.png)
