### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Erro mensagem de data inválida

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#86]
Na  tela de cadastro de gasto quando o usuário informa uma data inválida no campo Data da Emissão/Contratação o sistema apresenta a mensagem " Data de Emissão/Contratação Inválida.", porém a mensagem definida no documento  de mensagem é "Data Inválida".

**Comment by jadossantos** [comment]
Corrigido.

**Comment by marasb** [comment]
Defeito corrigido.
