### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Erro mensagem de valor total da descrição do gasto.

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#87]
O sistema está apresentando a mensagem de alerta "O Valor do Documento está diferente do Valor Total da Descrição do Gasto." mesmo quando o usuário não informa nenhum valor no campo "Valor do Documento".
![erro_mensagem de data](https://cloud.githubusercontent.com/assets/6304414/2711604/92471506-c4cf-11e3-96ff-a4233871597b.jpg)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido.
