### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Erro na mensagem de exceção após informada uma data inválida

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#88]
Quando o usuário não informa uma data inválida e aciona o botão gravar, o sistema apresenta a mensagem "Data inválida", porém quando acionado o botão Limpar e logo em seguida acionar o botão "Gravar", o sistema continua apresentando mensagem de data inválida, mesmo sem possuir nenhuma data no campo "Data da Emissão/Contratação ".
Passos:
![erro_data ivlida](https://cloud.githubusercontent.com/assets/6304414/2718859/02549ed2-c556-11e3-8a15-c3f469b5ef04.png)

1) Informar todos os campos obrigatórios.
2) Informar  uma data inválida.
3) Acionar o botão Limpar.
4) Acionar o botão "Gravar".
5) Verificar que o sistema continua apresentando a mensagem de data inválida.

**Comment by jadossantos** [comment]
Corrigido.

**Comment by marasb** [comment]
Defeito corrigido
