### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Sistema não está validando o campo CPF/CNPJ

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#89]
O sistema está aceitando informar um CPF/CNPJ inválido sem apresentar nenhuma mensagem de crítica.
O caso de uso define o seguinte:
O fluxo inicia quando o sistema verifica que o número do CPF/CNPJ informado é inválido.
FA 10.1.    O sistema apresenta a mensagem MSG084.
FA 10.2.    O ator confirma a mensagem.
FA 10.3.    O fluxo retorna ao passo FA 1.2 do fluxo FA 1 ou ao passo FA 2.3 do fluxo FA 2.

**Comment by jadossantos** [comment]
Corrigido.

**Comment by marasb** [comment]
Defeito corrigido.
