### ISSUE TITLE
HU_SPCA_Efetuar login no sistema - Erro na mensagem MSG064

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#9]
Após efetuar o login e selecionar o prestador de contas, o sistema está apresentando a mensagem "???prestador.conta.selecionado.popup??? 11 PP PARTIDO PROGRESSISTA. Confirma?"
Sendo que o correto é apresentar a mensagem MSG064 "Foi selecionado o prestador de contas <Número – Sigla – Nome do Partido>. Confirma?"
![erro na mensagem ao selecionar o prestador de contas](https://f.cloud.github.com/assets/6304414/1932048/465bb924-7ec7-11e3-882b-d91b568c50d6.jpg)

**Comment by AllanCruzRosa** [comment]
liberado para teste na versão 2.0.2

**Comment by marasb** [comment]
O erro persiste na versão 2.0.2.
![retorno bug09](https://f.cloud.github.com/assets/6304414/1934214/44cbf8e2-7ee7-11e3-8086-7d6f6c7f61a7.png)

**Comment by marasb** [comment]
O erro persiste na versão 2.0.2.
![retorno bug09](https://f.cloud.github.com/assets/6304414/1934225/78cbab10-7ee7-11e3-8cb0-d7eaa3d9cb13.png)

**Comment by flavioribeirom** [comment]
Liberado para teste

**Comment by marasb** [comment]
Defeito corrigido
