### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Caixa de Seleção campo e Operação não está sendo exibida em ordem alfabética crescente

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#90]
Na tela Pesquisa de Aplicação de Recurso os campo "Campo" e "Operação" não estão classificados em ordem alfabética crescente, indo contra o RAP21 e RAP22 que define:
"A lista de campo deve ser exibida em ordem alfabética crescente."
"A lista de operação deve ser exibida em ordem alfabética crescente."

![erro_ordenao dos campos de pesquisa](https://cloud.githubusercontent.com/assets/6304414/2719292/7af62b8c-c55e-11e3-9331-c9db4ee771f1.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 2.0.30

**Comment by marasb** [comment]
Defeito corrigido
