### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Sistema não retorna resultado na busca de acordo para alguns filtros

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#91]
Na tela de pesquisa de aplicação de recurso, o sistema não retorna resultado na busca quando o usuário informa os parâmetros de gasto abaixo :
CPF + Contém
CNPJ + Contém
CPF + Começado Por
CNPJ + Começado Por
CPF + Terminado Por
CNPJ + Terminado Por
CNPJ + Igual a
Tipo de Documento + Igual

![erro _ sistema nao retorna resultado para filtros de pesquisa](https://cloud.githubusercontent.com/assets/6304414/2719860/d19b6084-c567-11e3-9438-ba5146211603.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
RETORNO VERSÃO 2.0.31: O sistema continua apresentando erro para as situações:
Tipo de Documento + Igual a = Não retorna resultado
Tipo de Documento + Diferente = Retorna todos os resultados incluindo o diferente.
Fonte de Recurso + Igual a   = Não retorna resultado
Fonte de Recurso + Diferente de   = Não retorna resultado
Forma de Pagamento + Igual a = Não retorna resultado
Forma de Pagamento + Diferente de = Retorna todos os resultados incluindo o diferente.

**Comment by rsantanam** [comment]
Resolvido.
Versão2.0.32

**Comment by marasb** [comment]
defeito corrigido.
