### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Sistema não apresenta mensagem Data Inválida na tela de pesquisa

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#93]
Na tela de pesquisa de aplicação de recurso quando o usuário informa uma data inválida nos parâmetros de pesquisa, o sistema apaga a data digitada, porém no caso de uso está definido que deve ser apresentada a mensagem Data inválida.

**Comment by jadossantos** [comment]
Bom dia Mara,

Esse campo é criado dinâmicamente a dedender do tipo de informação que é selecionado no combo "Campo".

Dessa maneira, a depender do tipo do Campo a validação já é realizada não permitindo que  usuário informe uma informação inválida.

Creio que a usabilidade da tela não seja prejudicada por esse motivo. Uma vez que estamos antecipando um comportamento e não deixando que o usuário informe um dado invalido.

Além de que, evitamos que no momento da consulta ao tentarmos realizar uma conversão do dado invalido informado, teríamos problemas na consulta.

Poderíamos deixar isso como uma futura melhoria na tentativa de identificarmos uma possível solução para isso, visto que no momento não impacta a funcionalidade do sistema e o impacto para se alterar o comportamento desse componente não seria simples.

**Comment by marasb** [comment]
Joel,
Não posso cadastrar esse item como Melhoria, pois no caso de uso está explícito que a mensagem deve ser apresentada. Se eu cadastrar como melhoria o TSE vai abrir como erro.

**Comment by raphaelgalvao** [comment]
Boa tarde Mara,

Com quem poderíamos conversar para expor essa situação.

Nosso ponto de vista em muitas coisas, relacionado a documentação e regras a serem implementadas é que a forma como foi especificada, muitas vezes complica e onera o tempo de desenvolvimento.

Sei que existem falhas e deveríamos ter reportado isso anteriormente, mas vejo que existe uma restrição imensa de seguir exatamente o que está escrito ao pé da letra. E não sugerir ou propor melhorias ao gestor.

Esse componente que desenvolvemos, infelizmente tem esse "defeito" (que no nosso ponto de vista não é efetivamente um defeito e não prejudica a utilização da funcionalidade) apenas que estamos evitando e tratando um erro diferentemente do que o CDU pede.

Nós estamos tentando buscar uma solução para o problema, porém não será rápida.

Com quem poderia entrar em contato para explicar a situação?

**Comment by marasb** [comment]
Nessa caso vocês devem falar com a Stella, para que seja avaliada essa situação com o Gestor e se for o caso alterar o caso de uso.

**Comment by jadossantos** [comment]
Mara,
A solução proposta na imagem abaixo atende ao requisito?

![spca gasto tela de pesquisa com data invalida](https://cloud.githubusercontent.com/assets/7116054/2767474/7ce96402-ca38-11e3-9422-f637a1e5fa20.png)

**Comment by marasb** [comment]
Joel,
Podemos tentar essa solução, visto que a mensagem atende ao requisito.
O que pode acontecer é eles questionarem quanto ao padrão de apresentação da mensagem.
Mas vamos tentar essa solução.

**Comment by jadossantos** [comment]
A solução foi implementada.

**Comment by marasb** [comment]
Defeito corrigido.
