### ISSUE TITLE
CDU_SPCA_026_Manter_Registro_do_Pagamento - Exibição da Mensagem

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#95]
Verificar o comportamento do sistema, pois ao simular  o fluxo [FE 3 - Data inicial do período maior que  a data final do período] o sistema não emitiu a mensagem conforme especificado na documentação.

![pesquisa](https://cloud.githubusercontent.com/assets/6584772/2720819/722d6e5a-c574-11e3-9d09-dabe0b6327b5.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Verificado a correção.

![corrigido](https://cloud.githubusercontent.com/assets/6584772/2722759/007f9324-c58c-11e3-9be9-5af6772e9239.png)
