### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Mensagem incorreta quando o sistema nao encontra dados para o resultado de pesquisa

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#96]
Quando o sistema não encontra resultados para a pesquisa de aplicação de recurso o sistema está apresentando a mensagem "Nenhum registro encontrado.", porém deve ser apresentada a mensagem "Não existe registro para o parâmetro informado."

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido
