### ISSUE TITLE
CDU_SPCA_026_Manter_Registro_do_Pagamento - Edição do Campo

### ISSUE THREAD

**Issue by jmatil** [islssa/SPCA#97]
O sistema não está permitindo a edição do campo "Valor" para simulação do fluxo [FE 2 - Data Inválida]

![datainvalida](https://cloud.githubusercontent.com/assets/6584772/2723199/4521218c-c591-11e3-94a4-a8118cd7777f.png)

**Comment by jadossantos** [comment]
Ticket duplicado (issues/93).

**Comment by marasb** [comment]
Defeito corrigido.
