### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Sistema está gravando registro mesmo quando o usuário não confirma a operação.

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#98]
O sistema está realizando a gravação do registro de gasto mesmo quando o usuário não confirma a operação.
Passos:
1) Informar todos os campos obrigatórios
2) Acionar o botão gravar
3) Não confirmar a mensagem de pagamento.
4) Não confirmar a mensagem de gravação MSG007

**Comment by jadossantos** [comment]
O item não estava explicito no CDU, porém é um comportamento padrão do sistema.

**Comment by jadossantos** [comment]
Feito.

**Comment by marasb** [comment]
Retorno: Ao selecionar a opção não confirmar  na mensagem "Confirma a operação", o sistema apresenta rapidamente a mensagem "Deseja registrar pagamento?" e logo desaparece.

**Comment by jadossantos** [comment]
Resolvido na versão 2.0.33.

**Comment by marasb** [comment]
Defeito corrigido.
