### ISSUE TITLE
CDU_SPCA_025_Manter_Registro_do_Gasto - Na tela de alteração está sendo apresentada a mensagem MSG077

### ISSUE THREAD

**Issue by marasb** [islssa/SPCA#99]
Na tela de ALTERAÇÃO de gasto, quando o usuário confirma a mensagem MSG007 "Confirma operação?" o sistema está apresentando a mensagem MSG077 "Deseja registrar pagamento?", porém no caso de de uso está descrito que a mensagem MSG077 deve ser apresentada somente quando o valor do documento for diferente do somatório dos valores do pagamento. (FA11)

**Comment by jadossantos** [comment]
Corrigido.

**Comment by marasb** [comment]
Defeito corrigido.
